/*
 * The MIT License

 * Copyright (c) 2023 Rido

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. 
 */

package net.chefcraft.reflection.world;

import net.chefcraft.core.server.ServerVersion;
import net.chefcraft.core.util.JHelper;
import net.chefcraft.core.util.Numbers;
import net.chefcraft.world.translatable.TranslatableItemStack;
import net.chefcraft.world.util.BukkitUtils;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.block.BlockState;
import org.bukkit.inventory.ItemStack;
import org.bukkit.material.MaterialData;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.logging.Level;

/**
 *  "CoreMaterial" is based on support for items up to 1.8. Its working logic is simple;
 *  if there is a desired material, it gives it, otherwise it transforms it
 *  into materials that are similar or functionally similar. The main purpose
 *  is to avoid getting a "null" error and to eliminate the trouble of adjusting
 *  the material while loading the config settings every time the server version changes.
 *  
 *  @Version 1.2
 *  @Since 1.0
 */
public enum CoreMaterial {
	
	ACACIA_BOAT("BOAT_ACACIA", "BOAT"),
	ACACIA_BUTTON("WOOD_BUTTON"),
	ACACIA_CHEST_BOAT(true, "ACACIA_BOAT", "BOAT_ACACIA", "BOAT"),
	ACACIA_DOOR("ACACIA_DOOR"),
	ACACIA_FENCE,
	ACACIA_FENCE_GATE,
	ACACIA_HANGING_SIGN(true, "ACACIA_SIGN", "SIGN"),
	ACACIA_LEAVES("LEAVES_2"),
	ACACIA_LOG("LOG_2"),
	ACACIA_PLANKS(4, "WOOD"),
	ACACIA_PRESSURE_PLATE("WOOD_PLATE"),
	ACACIA_SAPLING(4, "SAPLING"),
	ACACIA_SIGN("SIGN"),
	ACACIA_SLAB(4, "WOOD_STEP"),
	ACACIA_STAIRS,
	ACACIA_TRAPDOOR("TRAP_DOOR"),
	ACACIA_WALL_HANGING_SIGN(true, "ACACIA_WALL_SIGN", "WALL_SIGN"),
	ACACIA_WALL_SIGN("WALL_SIGN"),
	ACACIA_WOOD(12, "LOG_2"),
	ACTIVATOR_RAIL,
	AIR,
	ALLAY_SPAWN_EGG(94, true, "SQUID_SPAWN_EGG", "MONSTER_EGG"),
	ALLIUM(2, "RED_ROSE"),
	AMETHYST_BLOCK(true, "PRISMARINE"),
	AMETHYST_CLUSTER(true, "PRISMARINE_CRYSTALS"),
	AMETHYST_SHARD(true, "PRISMARINE_SHARD"),
	ANCIENT_DEBRIS(true, "NETHER_BRICKS", "NETHER_BRICK"),
	ANDESITE(5, "STONE"),
	ANDESITE_SLAB(true, "STONE_SLAB", "STEP"),
	ANDESITE_STAIRS(true, "COBBLESTONE_STAIRS"),
	ANDESITE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	ANGLER_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	ANVIL,
	APPLE,
	ARCHER_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	ARMOR_STAND,
	ARMS_UP_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	ARROW,
	ATTACHED_MELON_STEM("MELON_STEM"),
	ATTACHED_PUMPKIN_STEM("PUMPKIN_STEM"),
	AXOLOTL_BUCKET("WATER_BUCKET"),
	AXOLOTL_SPAWN_EGG(90, true, "PIG_SPAWN_EGG", "MONSTER_EGG"),
	AZALEA(true, "OAK_LEAVES", "LEAVES"),
	AZALEA_LEAVES(true, "OAK_LEAVES", "LEAVES"),
	AZURE_BLUET(3, "RED_ROSE"),
	BAKED_POTATO,
	BAMBOO(true, "STICK"),
	BAMBOO_BLOCK(true, "LOG"),
	BAMBOO_BUTTON(true, "OAK_BUTTON", "WOOD_BUTTON"),
	BAMBOO_CHEST_RAFT(true, "OAK_BOAT", "BOAT"),
	BAMBOO_DOOR(true, "OAK_DOOR", "WOOD_DOOR"),
	BAMBOO_FENCE(true, "OAK_FENCE", "FENCE"),
	BAMBOO_FENCE_GATE(true, "OAK_FENCE_GATE", "FENCE_GATE"),
	BAMBOO_HANGING_SIGN(true, "OAK_SIGN", "SIGN"),
	BAMBOO_MOSAIC(true, "LOG"),
	BAMBOO_MOSAIC_SLAB(true, "OAK_SLAB", "WOOD_STEP"),
	BAMBOO_MOSAIC_STAIRS(true, "OAK_STAIRS", "WOOD_STAIRS"),
	BAMBOO_PLANKS(true, "OAK_PLANKS", "WOOD"),
	BAMBOO_PRESSURE_PLATE(true, "WOOD_PLATE"),
	BAMBOO_RAFT(true, "OAK_BOAT", "BOAT"),
	BAMBOO_SAPLING(true, "OAK_SAPLING", "SAPLING"),
	BAMBOO_SIGN(true, "OAK_SIGN", "SIGN"),
	BAMBOO_SLAB(true, "OAK_SLAB", "WOOD_STEP"),
	BAMBOO_STAIRS(true, "OAK_STAIRS", "WOOD_STAIRS"),
	BAMBOO_TRAPDOOR(true, "OAK_TRAPDOOR", "TRAP_DOOR"),
	BAMBOO_WALL_HANGING_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	BAMBOO_WALL_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	BARREL(true, "CHEST"),
	BARRIER,
	BASALT(true, "COBBLESTONE"),
	BAT_SPAWN_EGG(65, "MONSTER_EGG"),
	BEACON,
	BEDROCK,
	BEE_NEST(true, "HAY_BLOCK"),
	BEE_SPAWN_EGG(98, true, "OCELOT_SPAWN_EGG", "MONSTER_EGG"),
	BEEF("RAW_BEEF"),
	BEEHIVE(true, "OAK_PLANKS", "WOOD"),
	BEETROOT(true, "WHEAT"),
	BEETROOT_SEEDS(true, "SEEDS"),
	BEETROOT_SOUP(true, "MUSHROOM_SOUP"),
	BEETROOTS(true, "BEETROOT_BLOCK", "HAY_BLOCK"),
	BELL(true, "NOTE_BLOCK"),
	BIG_DRIPLEAF(3, true, "LARGE_FERN", "DOUBLE_PLANT"),
	BIG_DRIPLEAF_STEM(3, true, "LARGE_FERN", "DOUBLE_PLANT"),
	BIRCH_BOAT("BOAT_BIRCH", "BOAT"),
	BIRCH_BUTTON("WOOD_BUTTON"),
	BIRCH_CHEST_BOAT(true, "BIRCH_BOAT", "BOAT_BIRCH", "BOAT"),
	BIRCH_DOOR("BIRCH_DOOR"),
	BIRCH_FENCE,
	BIRCH_FENCE_GATE,
	BIRCH_HANGING_SIGN(true, "BIRCH_SIGN", "SIGN"),
	BIRCH_LEAVES(2, "LEAVES"),
	BIRCH_LOG(2, "LOG"),
	BIRCH_PLANKS(2, "WOOD"),
	BIRCH_PRESSURE_PLATE("WOOD_PLATE"),
	BIRCH_SAPLING(2, "SAPLING"),
	BIRCH_SIGN("SIGN"),
	BIRCH_SLAB(2, "WOOD_STEP"),
	BIRCH_STAIRS("BIRCH_WOOD_STAIRS"),
	BIRCH_TRAPDOOR("TRAP_DOOR"),
	BIRCH_WALL_HANGING_SIGN(true, "BIRCH_WALL_SIGN", "WALL_SIGN"),
	BIRCH_WALL_SIGN("WALL_SIGN"),
	BIRCH_WOOD(2, "WOOD"),
	BLACK_BANNER("BANNER"),
	BLACK_BED(15, "BED"),
	BLACK_CANDLE(true, "TORCH"),
	BLACK_CANDLE_CAKE(true, "CAKE"),
	BLACK_CARPET(15, "CARPET"),
	BLACK_CONCRETE(15, "CONCRETE", "STAINED_CLAY"),
	BLACK_CONCRETE_POWDER(15, "CONCRETE_POWDER", "WOOL"),
	BLACK_DYE(true, "INK_SAC", "INK_SACK"),
	BLACK_GLAZED_TERRACOTTA(15, true, "STAINED_CLAY"),
	BLACK_SHULKER_BOX("CHEST"),
	BLACK_STAINED_GLASS(15, "STAINED_GLASS"),
	BLACK_STAINED_GLASS_PANE(15, "STAINED_GLASS_PANE"),
	BLACK_TERRACOTTA(15, "STAINED_CLAY"),
	BLACK_WALL_BANNER(0, "WALL_BANNER"),
	BLACK_WOOL(15, "WOOL"),
	BLACKSTONE(true, "COBBLESTONE"),
	BLACKSTONE_SLAB(3, true, "COBBLESTONE_SLAB", "STEP"),
	BLACKSTONE_STAIRS(true, "COBBLESTONE_STAIRS"),
	BLACKSTONE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	BLADE_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	BLAST_FURNACE(true, "FURNACE"),
	BLAZE_POWDER,
	BLAZE_ROD,
	BLAZE_SPAWN_EGG(61, "MONSTER_EGG"),
	BLUE_BANNER(4, "BANNER"),
	BLUE_BED(11, "BED"),
	BLUE_CANDLE(true, "TORCH"),
	BLUE_CANDLE_CAKE(true, "CAKE"),
	BLUE_CARPET(11, "CARPET"),
	BLUE_CONCRETE(11, "CONCRETE", "STAINED_CLAY"),
	BLUE_CONCRETE_POWDER(11, "CONCRETE_POWDER", "WOOL"),
	BLUE_DYE(4, "LAPIS_LAZULI", "INK_SACK"),
	BLUE_GLAZED_TERRACOTTA(11, true, "STAINED_CLAY"),
	BLUE_ICE("PACKED_ICE"),
	BLUE_ORCHID(1, "RED_ROSE"),
	BLUE_SHULKER_BOX(true, "CHEST"),
	BLUE_STAINED_GLASS(11, "STAINED_GLASS"),
	BLUE_STAINED_GLASS_PANE(11, "STAINED_GLASS_PANE"),
	BLUE_TERRACOTTA(11, "STAINED_CLAY"),
	BLUE_WALL_BANNER(4, "WALL_BANNER"),
	BLUE_WOOL(11, "WOOL"),
	BONE,
	BONE_BLOCK(15, true, "HUGE_MUSHROOM_2"),
	BONE_MEAL(15, "INK_SACK"),
	BOOK,
	BOOKSHELF,
	BOW,
	BOWL,
	BRAIN_CORAL(7, true, "RED_ROSE"),
	BRAIN_CORAL_BLOCK(6, true, "WOOL"),
	BRAIN_CORAL_FAN(7, true, "RED_ROSE"),
	BRAIN_CORAL_WALL_FAN(7, true, "RED_ROSE"),
	BREAD,
	BREWER_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	BREWING_STAND("BREWING_STAND"),
	BRICK("CLAY_BRICK"),
	BRICK_SLAB(4, "STEP"),
	BRICK_STAIRS,
	BRICK_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	BRICKS("BRICK"),
	BROWN_BANNER(3, "BANNER"),
	BROWN_BED(12, "BED"),
	BROWN_CANDLE(true, "TORCH"),
	BROWN_CANDLE_CAKE(true, "CAKE"),
	BROWN_CARPET(12, "CARPET"),
	BROWN_CONCRETE(12, "CONCRETE", "STAINED_CLAY"),
	BROWN_CONCRETE_POWDER(12, "CONCRETE_POWDER", "WOOL"),
	BROWN_DYE(1, true, "ORANGE_DYE", "INK_SACK"),
	BROWN_GLAZED_TERRACOTTA(12, true, "STAINED_CLAY"),
	BROWN_MUSHROOM,
	BROWN_MUSHROOM_BLOCK(14, "HUGE_MUSHROOM_1"),
	BROWN_SHULKER_BOX(true, "CHEST"),
	BROWN_STAINED_GLASS(12, "STAINED_GLASS"),
	BROWN_STAINED_GLASS_PANE(12, "STAINED_GLASS_PANE"),
	BROWN_TERRACOTTA(12, "STAINED_CLAY"),
	BROWN_WALL_BANNER(3, "WALL_BANNER"),
	BROWN_WOOL(12, "WOOL"),
	BRUSH(true, "STICK"),
	BUBBLE_COLUMN(true, "WATER"),
	BUBBLE_CORAL(2, true, "RED_ROSE"),
	BUBBLE_CORAL_BLOCK(10, true, "WOOL"),
	BUBBLE_CORAL_FAN(2, true, "RED_ROSE"),
	BUBBLE_CORAL_WALL_FAN(2, true, "RED_ROSE"),
	BUCKET,
	BUDDING_AMETHYST(1, true,"PRISMARINE"),
	BUNDLE(true, "LEATHER"),
	BURN_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	CACTUS,
	CAKE,
	CALCITE(3, true, "STONE"),
	CALIBRATED_SCULK_SENSOR(true, "SCULK_SENSOR", "DAYLIGHT_DETECTOR"),
	CAMEL_SPAWN_EGG(100, true, "HORSE_SPAWN_EGG", "MONSTER_EGG"),
	CAMPFIRE(true,"FIRE"),
	CANDLE(true,"TORCH"),
	CANDLE_CAKE(true, "CAKE"),
	CARROT("CARROT_ITEM"),
	CARROT_ON_A_STICK("CARROT_STICK"),
	CARROTS("CARROT"),
	CARTOGRAPHY_TABLE(true, "CRAFTING_TABLE", "WORKBENCH"),
	CARVED_PUMPKIN("PUMPKIN"),
	CAT_SPAWN_EGG(98, true, "OCELOT_SPAWN_EGG", "MONSTER_EGG"),
	CAULDRON("CAULDRON"),
	CAVE_AIR("AIR"),
	CAVE_SPIDER_SPAWN_EGG(59, "MONSTER_EGG"),
	CAVE_VINES("VINE"),
	CAVE_VINES_PLANT("VINE"),
	CHAIN("IRON_FENCE"),
	CHAIN_COMMAND_BLOCK("COMMAND_CHAIN", "COMMAND"),
	CHAINMAIL_BOOTS,
	CHAINMAIL_CHESTPLATE,
	CHAINMAIL_HELMET,
	CHAINMAIL_LEGGINGS,
	CHARCOAL(1, "COAL"),
	CHERRY_BOAT(true, "OAK_BOAT", "BOAT"),
	CHERRY_BUTTON(true, "OAK_BUTTON", "WOOD_BUTTON"),
	CHERRY_CHEST_BOAT(true, "OAK_BOAT", "BOAT"),
	CHERRY_DOOR(true, "WOOD_DOOR"),
	CHERRY_FENCE(true, "OAK_FENCE", "FENCE"),
	CHERRY_FENCE_GATE(true, "OAK_FENCE_GATE", "FENCE_GATE"),
	CHERRY_HANGING_SIGN(true, "OAK_SIGN", "SIGN"),
	CHERRY_LEAVES(true, "OAK_LEAVES", "LEAVES"),
	CHERRY_LOG(true, "OAK_LOG", "LOG"),
	CHERRY_PLANKS(true, "OAK_PLANKS", "WOOD"),
	CHERRY_PRESSURE_PLATE(true, "OAK_PRESSURE_PLATE", "WOOD_PLATE"),
	CHERRY_SAPLING(true, "OAK_SAPLING", "SAPLING"),
	CHERRY_SIGN(true, "OAK_SIGN", "SIGN"),
	CHERRY_SLAB(true, "OAK_SLAB", "WOOD_STEP"),
	CHERRY_STAIRS(true, "OAK_STAIRS", "WOOD_STAIRS"),
	CHERRY_TRAPDOOR(true, "OAK_TRAPDOOR", "TRAP_DOOR"),
	CHERRY_WALL_HANGING_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	CHERRY_WALL_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	CHERRY_WOOD(12, true,"OAK_WOOD", "LOG"),
	CHEST,
	CHEST_MINECART("STORAGE_MINECART"),
	CHICKEN("RAW_CHICKEN"),
	CHICKEN_SPAWN_EGG(93, "MONSTER_EGG"),
	CHIPPED_ANVIL(1, "ANVIL"),
	CHISELED_BOOKSHELF(true, "BOOKSHELF"),
	CHISELED_DEEPSLATE(3, true, "CHISELED_STONE_BRICKS", "SMOOTH_BRICK"),
	CHISELED_NETHER_BRICKS(true, "NETHER_BRICKS", "NETHER_BRICK"),
	CHISELED_POLISHED_BLACKSTONE(true, "CHISELED_STONE_BRICKS", "SMOOTH_BRICK"),
	CHISELED_QUARTZ_BLOCK(1, "QUARTZ_BLOCK"),
	CHISELED_RED_SANDSTONE(1, "RED_SANDSTONE"),
	CHISELED_SANDSTONE(1, "SANDSTONE"),
	CHISELED_STONE_BRICKS(3, "SMOOTH_BRICK"),
	CHORUS_FLOWER(7, true, "RED_ROSE"), //for 1.8
	CHORUS_FRUIT(7, true, "RED_ROSE"),  //for 1.8
	CHORUS_PLANT(1, true, "DOUBLE_PLANT"), //for 1.8
	CLAY,
	CLAY_BALL,
	CLOCK("WATCH"),
	COAL,
	COAL_BLOCK,
	COAL_ORE,
	COARSE_DIRT(1, "DIRT"),
	COAST_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	COBBLED_DEEPSLATE(true, "COBBLESTONE"),
	COBBLED_DEEPSLATE_SLAB(3, true, "COBBLESTONE_SLAB", "STEP"),
	COBBLED_DEEPSLATE_STAIRS(true, "COBBLESTONE_STAIRS"),
	COBBLED_DEEPSLATE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	COBBLESTONE,
	COBBLESTONE_SLAB(3, "STEP"),
	COBBLESTONE_STAIRS,
	COBBLESTONE_WALL("COBBLE_WALL"),
	COBWEB("WEB"),
	COCOA,
	COCOA_BEANS(3, "INK_SACK"),
	COD("RAW_FISH"),
	COD_BUCKET(true, "WATER_BUCKET"),
	COD_SPAWN_EGG(101, true, "MONSTER_EGG"),
	COMMAND_BLOCK("COMMAND"),
	COMMAND_BLOCK_MINECART("COMMAND_MINECART"),
	COMPARATOR("REDSTONE_COMPARATOR"),
	COMPASS,
	COMPOSTER(true, "CAULDRON"),
	CONDUIT(3, true, "SKULL_ITEM"),
	COOKED_BEEF,
	COOKED_CHICKEN,
	COOKED_COD(true, "COOKED_FISH"),
	COOKED_MUTTON,
	COOKED_PORKCHOP("GRILLED_PORK"),
	COOKED_RABBIT,
	COOKED_SALMON(true, "COOKED_FISH"),
	COOKIE,
	COPPER_BLOCK(true, "IRON_BLOCK"),
	COPPER_INGOT(true, "IRON_INGOT"),
	COPPER_ORE(true, "IRON_ORE"),
	CORNFLOWER(1, true, "BLUE_ORCHID", "RED_ROSE"),
	COW_SPAWN_EGG(92, "MONSTER_EGG"),
	CRACKED_DEEPSLATE_BRICKS(2, true, "SMOOTH_BRICK"),
	CRACKED_DEEPSLATE_TILES(true, "BRICK"),
	CRACKED_NETHER_BRICKS(true, "NETHER_BRICK"),
	CRACKED_POLISHED_BLACKSTONE_BRICKS(true, "OBSIDIAN"),
	CRACKED_STONE_BRICKS(2, "SMOOTH_BRICK"),
	CRAFTING_TABLE("WORKBENCH"),
	CREEPER_BANNER_PATTERN(true, "PAPER"),
	CREEPER_HEAD(1, "SKULL"),
	CREEPER_SPAWN_EGG(50, "MONSTER_EGG"),
	CREEPER_WALL_HEAD(4, "SKULL"),
	CRIMSON_BUTTON(true, "OAK_BUTTON", "WOOD_BUTTON"),
	CRIMSON_DOOR(true, "OAK_DOOR", "WOODEN_DOOR"),
	CRIMSON_FENCE(true, "OAK_FENCE", "FENCE"),
	CRIMSON_FENCE_GATE(true, "OAK_FENCE_GATE", "FENCE_GATE"),
	CRIMSON_FUNGUS(true, "RED_MUSHROOM"),
	CRIMSON_HANGING_SIGN(true, "OAK_SIGN", "SIGN"),
	CRIMSON_HYPHAE(12, true, "LOG"),
	CRIMSON_NYLIUM(true, "NETHERRACK"),
	CRIMSON_PLANKS(true, "OAK_PLANKS", "WOOD"),
	CRIMSON_PRESSURE_PLATE(true, "OAK_PRESSURE_PLATE", "WOOD_PLATE"),
	CRIMSON_ROOTS(1, true, "LONG_GRASS"),
	CRIMSON_SIGN(true, "OAK_SIGN", "SIGN"),
	CRIMSON_SLAB(true, "OAK_SLAB", "WOOD_STEP"),
	CRIMSON_STAIRS(true, "OAK_STAIRS", "WOOD_STAIRS"),
	CRIMSON_STEM(true, "OAK_LOG", "LOG"),
	CRIMSON_TRAPDOOR(true, "OAK_TRAPDOOR", "TRAP_DOOR"),
	CRIMSON_WALL_HANGING_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	CRIMSON_WALL_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	CROSSBOW(true, "BOW"),
	CRYING_OBSIDIAN(true, "OBSIDIAN"),
	CUT_COPPER(true, "RED_SANDSTONE"),
	CUT_COPPER_SLAB(true, "RED_SANDSTONE_SLAB", "STONE_SLAB2"),
	CUT_COPPER_STAIRS(true, "RED_SANDSTONE_STAIRS"),
	CUT_RED_SANDSTONE(2, "RED_SANDSTONE"),
	CUT_RED_SANDSTONE_SLAB(true, "RED_SANDSTONE_SLAB", "STONE_SLAB2"),
	CUT_SANDSTONE(2, "SANDSTONE"),
	CUT_SANDSTONE_SLAB(1, true, "STEP"),
	CYAN_BANNER(6, "BANNER"),
	CYAN_BED(9, "BED"),
	CYAN_CANDLE(true, "TORCH"),
	CYAN_CANDLE_CAKE(true, "CAKE"),
	CYAN_CARPET(9, "CARPET"),
	CYAN_CONCRETE(9, "CONCRETE", "STAINED_CLAY"),
	CYAN_CONCRETE_POWDER(9, "CONCRETE_POWDER", "WOOL"),
	CYAN_DYE(6, "INK_SACK"),
	CYAN_GLAZED_TERRACOTTA(9, true, "STAINED_CLAY"),
	CYAN_SHULKER_BOX(true, "CHEST"),
	CYAN_STAINED_GLASS(9, "STAINED_GLASS"),
	CYAN_STAINED_GLASS_PANE(9, "STAINED_GLASS_PANE"),
	CYAN_TERRACOTTA(9, "STAINED_CLAY"),
	CYAN_WALL_BANNER(6, "BANNER"),
	CYAN_WOOL(9, "WOOL"),
	DAMAGED_ANVIL(2, "ANVIL"),
	DANDELION("YELLOW_FLOWER"),
	DANGER_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	DARK_OAK_BOAT(1, "LOG_2"),
	DARK_OAK_BUTTON("WOOD_BUTTON"),
	DARK_OAK_CHEST_BOAT("BOAT_DARK_OAK", "BOAT"),
	DARK_OAK_DOOR,
	DARK_OAK_FENCE,
	DARK_OAK_FENCE_GATE,
	DARK_OAK_HANGING_SIGN(true, "DARK_OAK_SIGN", "SIGN"),
	DARK_OAK_LEAVES(1, "LEAVES_2"),
	DARK_OAK_LOG(1, "LOG_2"),
	DARK_OAK_PLANKS(5, "WOOD"),
	DARK_OAK_PRESSURE_PLATE(true, "WOOD_PLATE"),
	DARK_OAK_SAPLING(5, "SAPLING"),
	DARK_OAK_SIGN(true, "SIGN"),
	DARK_OAK_SLAB(5, "WOOD_STEP"),
	DARK_OAK_STAIRS,
	DARK_OAK_TRAPDOOR(true, "TRAP_DOOR"),
	DARK_OAK_WALL_HANGING_SIGN(true, "DARK_OAK_WALL_SIGN", "WALL_SIGN"),
	DARK_OAK_WALL_SIGN(true, "WALL_SIGN"),
	DARK_OAK_WOOD(13, "LOG_2"),
	DARK_PRISMARINE(2, "PRISMARINE"),
	DARK_PRISMARINE_SLAB(3, true, "STEP"),
	DARK_PRISMARINE_STAIRS(true, "COBBLESTONE_STAIRS"),
	DAYLIGHT_DETECTOR,
	DEAD_BRAIN_CORAL(true, "DEAD_BUSH"),
	DEAD_BRAIN_CORAL_BLOCK(8, true, "WOOL"),
	DEAD_BRAIN_CORAL_FAN(true, "DEAD_BUSH"),
	DEAD_BRAIN_CORAL_WALL_FAN(true, "DEAD_BUSH"),
	DEAD_BUBBLE_CORAL(true, "DEAD_BUSH"),
	DEAD_BUBBLE_CORAL_BLOCK(8, true, "WOOL"),
	DEAD_BUBBLE_CORAL_FAN(true, "DEAD_BUSH"),
	DEAD_BUBBLE_CORAL_WALL_FAN(true, "DEAD_BUSH"),
	DEAD_BUSH,
	DEAD_FIRE_CORAL(true, "DEAD_BUSH"),
	DEAD_FIRE_CORAL_BLOCK(8, true, "WOOL"),
	DEAD_FIRE_CORAL_FAN(true, "DEAD_BUSH"),
	DEAD_FIRE_CORAL_WALL_FAN(true, "DEAD_BUSH"),
	DEAD_HORN_CORAL(true, "DEAD_BUSH"),
	DEAD_HORN_CORAL_BLOCK(8, true, "WOOL"),
	DEAD_HORN_CORAL_FAN(true, "DEAD_BUSH"),
	DEAD_HORN_CORAL_WALL_FAN(true, "DEAD_BUSH"),
	DEAD_TUBE_CORAL(true, "DEAD_BUSH"),
	DEAD_TUBE_CORAL_BLOCK(8, true, "WOOL"),
	DEAD_TUBE_CORAL_FAN(true, "DEAD_BUSH"),
	DEAD_TUBE_CORAL_WALL_FAN(true, "DEAD_BUSH"),
	DEBUG_STICK(true, "STICK"),
	DECORATED_POT(true, "FLOWER_POT"),
	DEEPSLATE(true, "COBBLESTONE"),
	DEEPSLATE_BRICK_SLAB(5, true, "STONE_BRICK_SLAB", "STEP"),
	DEEPSLATE_BRICK_STAIRS(true, "SMOOTH_STAIRS"),
	DEEPSLATE_BRICK_WALL(true, "COBBLE_WALL"),
	DEEPSLATE_BRICKS(true, "SMOOTH_BRICK"),
	DEEPSLATE_COAL_ORE(true, "COAL_ORE"),
	DEEPSLATE_COPPER_ORE(true, "IRON_ORE"),
	DEEPSLATE_DIAMOND_ORE(true, "DIAMOND_ORE"),
	DEEPSLATE_EMERALD_ORE(true, "EMERALD_ORE"),
	DEEPSLATE_GOLD_ORE(true, "GOLD_ORE"),
	DEEPSLATE_IRON_ORE(true, "IRON_ORE"),
	DEEPSLATE_LAPIS_ORE(true, "LAPIS_ORE"),
	DEEPSLATE_REDSTONE_ORE(true, "REDSTONE_ORE"),
	DEEPSLATE_TILE_SLAB(4, true, "BRICK_SLAB", "STEP"),
	DEEPSLATE_TILE_STAIRS(true, "BRICK_STAIRS"),
	DEEPSLATE_TILE_WALL(1, true, "COBBLE_WALL"),
	DEEPSLATE_TILES(true, "BRICKS", "BRICK"),
	DETECTOR_RAIL,
	DIAMOND,
	DIAMOND_AXE,
	DIAMOND_BLOCK,
	DIAMOND_BOOTS,
	DIAMOND_CHESTPLATE,
	DIAMOND_HELMET,
	DIAMOND_HOE,
	DIAMOND_HORSE_ARMOR("DIAMOND_BARDING"),
	DIAMOND_LEGGINGS,
	DIAMOND_ORE,
	DIAMOND_PICKAXE,
	DIAMOND_SHOVEL("DIAMOND_SPADE"),
	DIAMOND_SWORD,
	DIORITE(3, "STONE"),
	DIORITE_SLAB(3, true, "STEP"),
	DIORITE_STAIRS(true, "COBBLESTONE_STAIRS"),
	DIORITE_WALL(true, "COBBLE_WALL"),
	DIRT,
	DIRT_PATH(true, "GRASS_PATH", "GRASS"),
	DISC_FRAGMENT_5(true, "RECORD_11"),
	DISPENSER,
	DOLPHIN_SPAWN_EGG(94, true, "MONSTER_EGG"),
	DONKEY_SPAWN_EGG(92, true, "MONSTER_EGG"),
	DRAGON_BREATH(1, "DRAGONS_BREATH", "POTION"), //for 1.8
	DRAGON_EGG,
	DRAGON_HEAD(true, "SKULL"),
	DRAGON_WALL_HEAD(3, true, "SKULL"),
	DRIED_KELP(1, true, "COAL"),
	DRIED_KELP_BLOCK(13, true, "WOOL"),
	DRIPSTONE_BLOCK(1, true, "STONE"),
	DROPPER,
	DROWNED_SPAWN_EGG(54, true, "MONSTER_EGG"),
	DUNE_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	ECHO_SHARD(true, "PRISMARINE_SHARD"),
	EGG,
	ELDER_GUARDIAN_SPAWN_EGG(68, true, "MONSTER_EGG"),
	ELYTRA(true, "LEATHER_CHESTPLATE"), //for 1.8
	EMERALD,
	EMERALD_BLOCK,
	EMERALD_ORE,
	ENCHANTED_BOOK,
	ENCHANTED_GOLDEN_APPLE(1, "GOLDEN_APPLE"),
	ENCHANTING_TABLE("ENCHANTMENT_TABLE"),
	END_CRYSTAL(true, "NETHER_STAR"), //for 1.8
	END_GATEWAY(true, "ENDER_PORTAL"), //for 1.8
	END_PORTAL("ENDER_PORTAL"),
	END_PORTAL_FRAME("ENDER_PORTAL_FRAME"),
	END_ROD(true, "TORCH"), //for 1.8
	END_STONE("ENDER_STONE"),
	END_STONE_BRICK_SLAB(1, true, "STEP"),
	END_STONE_BRICK_STAIRS(true, "SANDSTONE_STAIRS"),
	END_STONE_BRICK_WALL(true, "COBBLE_WALL"),
	END_STONE_BRICKS("END_BRICKS", "ENDER_STONE"), //@ENDER_STONE for 1.8
	ENDER_CHEST,
	ENDER_DRAGON_SPAWN_EGG("DRAGON_EGG"),
	ENDER_EYE("EYE_OF_ENDER"),
	ENDER_PEARL,
	ENDERMAN_SPAWN_EGG(58, "MONSTER_EGG"),
	ENDERMITE_SPAWN_EGG(67, "MONSTER_EGG"),
	EVOKER_SPAWN_EGG(ServerVersion.current().isHigherThan(ServerVersion.v1_10_2) ? 34 : 94, "MONSTER_EGG"),
	EXPERIENCE_BOTTLE("EXP_BOTTLE"),
	EXPLORER_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	EXPOSED_COPPER(true, "RED_SANDSTONE"),
	EXPOSED_CUT_COPPER(1, true, "RED_SANDSTONE"),
	EXPOSED_CUT_COPPER_SLAB(true, "RED_SANDSTONE_SLAB", "STONE_SLAB2"),
	EXPOSED_CUT_COPPER_STAIRS(true, "RED_SANDSTONE_STAIRS"),
	EYE_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	FARMLAND("SOIL"),
	FEATHER,
	FERMENTED_SPIDER_EYE,
	FERN(2, "LONG_GRASS"),
	FILLED_MAP("MAP"),
	FIRE,
	FIRE_CHARGE("FIREBALL"),
	FIRE_CORAL(4, true, "DOUBLE_PLANT"),
	FIRE_CORAL_BLOCK(14, true, "WOOL"),
	FIRE_CORAL_FAN(true, "RED_ROSE"),
	FIRE_CORAL_WALL_FAN(true, "RED_ROSE"),
	FIREWORK_ROCKET("FIREWORK"),
	FIREWORK_STAR("FIREWORK_CHARGE"),
	FISHING_ROD,
	FLETCHING_TABLE(true, "CRAFTING_TABLE", "WORKBENCH"),
	FLINT,
	FLINT_AND_STEEL,
	FLOWER_BANNER_PATTERN(true, "PAPER"),
	FLOWER_POT,
	FLOWERING_AZALEA(3, true, "LEAVES"),
	FLOWERING_AZALEA_LEAVES(3, true, "LEAVES"),
	FOX_SPAWN_EGG(95, true, "WOLF_SPAWN_EGG", "MONSTER_EGG"),
	FRIEND_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	FROG_SPAWN_EGG(101, true, "RABBIT_SPAWN_EGG", "MONSTER_EGG"),
	FROGSPAWN(true, "LILY_PAD", "WATER_LILY"),
	FROSTED_ICE(true, "ICE"),
	FURNACE,
	FURNACE_MINECART("POWERED_MINECART"),
	GHAST_SPAWN_EGG(56, "MONSTER_EGG"),
	GHAST_TEAR(),
	GILDED_BLACKSTONE(15, true, "BLACK_WOOL", "WOOL"),
	GLASS,
	GLASS_BOTTLE,
	GLASS_PANE("THIN_GLASS"),
	GLISTERING_MELON_SLICE("SPECKLED_MELON"),
	GLOBE_BANNER_PATTERN(true, "PAPER"),
	GLOW_BERRIES(true, "MELON_SLICE", "MELON"),
	GLOW_INK_SAC(true, "INK_SACK", "INK_SACK"),
	GLOW_ITEM_FRAME(true, "ITEM_FRAME"),
	GLOW_LICHEN(true, "VINE"),
	GLOW_SQUID_SPAWN_EGG(94, true, "SQUID_SPAWN_EGG", "MONSTER_EGG"),
	GLOWSTONE,
	GLOWSTONE_DUST,
	GOAT_HORN(true, "RABBIT_FOOT"),
	GOAT_SPAWN_EGG(91, true, "SHEEP_SPAWN_EGG", "MONSTER_EGG"),
	GOLD_BLOCK,
	GOLD_INGOT,
	GOLD_NUGGET,
	GOLD_ORE,
	GOLDEN_APPLE,
	GOLDEN_AXE("GOLD_AXE"),
	GOLDEN_BOOTS("GOLD_BOOTS"),
	GOLDEN_CARROT,
	GOLDEN_CHESTPLATE("GOLD_CHESTPLATE"),
	GOLDEN_HELMET("GOLD_HELMET"),
	GOLDEN_HOE("GOLD_HOE"),
	GOLDEN_HORSE_ARMOR("GOLD_BARDING"),
	GOLDEN_LEGGINGS("GOLD_LEGGINGS"),
	GOLDEN_PICKAXE("GOLD_PICKAXE"),
	GOLDEN_SHOVEL("GOLD_SPADE"),
	GOLDEN_SWORD("GOLD_SWORD"),
	GRANITE(1, "STONE"),
	GRANITE_SLAB(3, true, "COBBLESTONE_SLAB", "STEP"),
	GRANITE_STAIRS(true, "COBBLESTONE_STAIRS"),
	GRANITE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	GRASS_BLOCK("GRASS"),
	GRAVEL,
	GRAY_BANNER(8, "BANNER"),
	GRAY_BED(7, "BED"),
	GRAY_CANDLE(true, "TORCH"),
	GRAY_CANDLE_CAKE(true, "CAKE"),
	GRAY_CARPET(7, "CARPET"),
	GRAY_CONCRETE(7, "CONCRETE", "STAINED_CLAY"),
	GRAY_CONCRETE_POWDER(7, "CONCRETE_POWDER", "WOOL"),
	GRAY_DYE(8, "INK_SACK"),
	GRAY_GLAZED_TERRACOTTA(7, true, "STAINED_CLAY"),
	GRAY_SHULKER_BOX(true, "CHEST"),
	GRAY_STAINED_GLASS(7, "STAINED_GLASS"),
	GRAY_STAINED_GLASS_PANE(7, "STAINED_GLASS_PANE"),
	GRAY_TERRACOTTA(7, "STAINED_CLAY"),
	GRAY_WALL_BANNER(8, "BANNER"),
	GRAY_WOOL(7, "WOOL"),
	GREEN_BANNER(2, "BANNER"),
	GREEN_BED(13, "BED"),
	GREEN_CANDLE(true, "TORCH"),
	GREEN_CANDLE_CAKE(true, "CAKE"),
	GREEN_CARPET(13, "CARPET"),
	GREEN_CONCRETE(13, "CONCRETE", "STAINED_CLAY"),
	GREEN_CONCRETE_POWDER(13, "CONCRETE_POWDER", "WOOL"),
	GREEN_DYE(2, "INK_SACK"),
	GREEN_GLAZED_TERRACOTTA(13, true, "STAINED_CLAY"),
	GREEN_SHULKER_BOX(true, "CHEST"),
	GREEN_STAINED_GLASS(13, "STAINED_GLASS"),
	GREEN_STAINED_GLASS_PANE(13, "STAINED_GLASS_PANE"),
	GREEN_TERRACOTTA(13, "STAINED_CLAY"),
	GREEN_WALL_BANNER(2, "WALL_BANNER"),
	GREEN_WOOL(13, "WOOL"),
	GRINDSTONE(true, "TRIPWIRE_HOOK"),
	GUARDIAN_SPAWN_EGG(68, "MONSTER_EGG"),
	GUNPOWDER("SULPHUR"),
	HANGING_ROOTS(true, "DEAD_BUSH"),
	HAY_BLOCK,
	HEART_OF_THE_SEA(12, true, "INK_SACK"),
	HEART_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	HEARTBREAK_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	HEAVY_WEIGHTED_PRESSURE_PLATE("IRON_PLATE"),
	HOGLIN_SPAWN_EGG(90, true, "PIG_SPAWN_EGG", "MONSTER_EGG"),
	HONEY_BLOCK(true, "SLIME_BLOCK"),
	HONEY_BOTTLE(true, "GLASS_BOTTLE"),
	HONEYCOMB(5, true, "ORANGE_TULIP", "RED_ROSE"),
	HONEYCOMB_BLOCK(1, true, "ORANGE_WOOL", "WOOL"),
	HOPPER,
	HOPPER_MINECART,
	HORN_CORAL(true, "DANDELION", "YELLOW_FLOWER"),
	HORN_CORAL_BLOCK(true, "SPONGE"),
	HORN_CORAL_FAN(true, "DANDELION", "YELLOW_FLOWER"),
	HORN_CORAL_WALL_FAN(true, "DANDELION", "YELLOW_FLOWER"),
	HORSE_SPAWN_EGG(100, "MONSTER_EGG"),
	HOST_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	HOWL_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	HUSK_SPAWN_EGG(23, "MONSTER_EGG"),
	ICE,
	INFESTED_CHISELED_STONE_BRICKS(5, "MONSTER_EGGS"),
	INFESTED_COBBLESTONE(1, "MONSTER_EGGS"),
	INFESTED_CRACKED_STONE_BRICKS(4, "MONSTER_EGGS"),
	INFESTED_DEEPSLATE(1, true, "INFESTED_COBBLESTONE", "MONSTER_EGGS"),
	INFESTED_MOSSY_STONE_BRICKS(3, "MONSTER_EGGS"),
	INFESTED_STONE("MONSTER_EGGS"),
	INFESTED_STONE_BRICKS(2, "MONSTER_EGGS"),
	INK_SAC("INK_SACK"),
	IRON_AXE,
	IRON_BARS("IRON_FENCE"),
	IRON_BLOCK,
	IRON_BOOTS,
	IRON_CHESTPLATE,
	IRON_DOOR,
	IRON_GOLEM_SPAWN_EGG(95, "MONSTER_EGG"),
	IRON_HELMET,
	IRON_HOE,
	IRON_HORSE_ARMOR("IRON_BARDING"),
	IRON_INGOT,
	IRON_LEGGINGS,
	IRON_NUGGET(true, "IRON_INGOT"),
	IRON_ORE,
	IRON_PICKAXE,
	IRON_SHOVEL("IRON_SPADE"),
	IRON_SWORD,
	IRON_TRAPDOOR,
	ITEM_FRAME,
	JACK_O_LANTERN,
	JIGSAW(true, "STRUCTURE_BLOCK", "COMMAND"),
	JUKEBOX,
	JUNGLE_BOAT("BOAT_JUNGLE", "BOAT"),
	JUNGLE_BUTTON("WOOD_BUTTON"),
	JUNGLE_CHEST_BOAT(true, "JUNGLE_BOAT", "BOAT_JUNGLE", "BOAT"),
	JUNGLE_DOOR,
	JUNGLE_FENCE,
	JUNGLE_FENCE_GATE,
	JUNGLE_HANGING_SIGN(true, "JUNGLE_SIGN", "SIGN"),
	JUNGLE_LEAVES(3, "LEAVES"),
	JUNGLE_LOG(3, "LOG"),
	JUNGLE_PLANKS(3, "WOOD"),
	JUNGLE_PRESSURE_PLATE("WOOD_PLATE"),
	JUNGLE_SAPLING(3, "SAPLING"),
	JUNGLE_SIGN("SIGN"),
	JUNGLE_SLAB(3, "WOOD_STEP"),
	JUNGLE_STAIRS("JUNGLE_WOOD_STAIRS"),
	JUNGLE_TRAPDOOR("TRAP_DOOR"),
	JUNGLE_WALL_HANGING_SIGN(true, "JUNGLE_WALL_SIGN", "WALL_SIGN"),
	JUNGLE_WALL_SIGN("WALL_SIGN"),
	JUNGLE_WOOD(15, "LOG"),
	KELP(true, "SUGAR_CANE"),
	KELP_PLANT(true, "SUGAR_CANE_BLOCK"),
	KNOWLEDGE_BOOK(true, "BOOK"),
	LADDER,
	LANTERN("SEA_LANTERN"),
	LAPIS_BLOCK,
	LAPIS_LAZULI(4, "INK_SACK"),
	LAPIS_ORE,
	LARGE_AMETHYST_BUD("PRISMARINE_CRYSTALS"),
	LARGE_FERN(3, "DOUBLE_PLANT"),
	LAVA,
	LAVA_BUCKET,
	LAVA_CAULDRON(true, "CAULDRON"),
	LEAD("LEASH"),
	LEATHER,
	LEATHER_BOOTS,
	LEATHER_CHESTPLATE,
	LEATHER_HELMET,
	LEATHER_HORSE_ARMOR(true, "GOLD_BARDING"),
	LEATHER_LEGGINGS,
	LECTERN(true, "BOOKSHELF"),
	LEVER,
	LIGHT(true, "AIR"),
	LIGHT_BLUE_BANNER(12, "BANNER"),
	LIGHT_BLUE_BED(3, "BED"),
	LIGHT_BLUE_CANDLE(true, "TORCH"),
	LIGHT_BLUE_CANDLE_CAKE(true, "CAKE"),
	LIGHT_BLUE_CARPET(3, "CARPET"),
	LIGHT_BLUE_CONCRETE(3, "CONCRETE", "STAINED_CLAY"),
	LIGHT_BLUE_CONCRETE_POWDER(3, "CONCRETE_POWDER", "WOOL"),
	LIGHT_BLUE_DYE(12, "INK_SACK"),
	LIGHT_BLUE_GLAZED_TERRACOTTA(3, true, "STAINED_CLAY"),
	LIGHT_BLUE_SHULKER_BOX(true, "CHEST"),
	LIGHT_BLUE_STAINED_GLASS(3, "STAINED_GLASS"),
	LIGHT_BLUE_STAINED_GLASS_PANE(3, "STAINED_GLASS_PANE"),
	LIGHT_BLUE_TERRACOTTA(3, "STAINED_CLAY"),
	LIGHT_BLUE_WALL_BANNER(12, "WALL_BANNER"),
	LIGHT_BLUE_WOOL(3, "WOOL"),
	LIGHT_GRAY_BANNER(7, "BANNER"),
	LIGHT_GRAY_BED(8, "BED"),
	LIGHT_GRAY_CANDLE(true, "TORCH"),
	LIGHT_GRAY_CANDLE_CAKE(true, "CAKE"),
	LIGHT_GRAY_CARPET(8, "CARPET"),
	LIGHT_GRAY_CONCRETE(8, "CONCRETE", "STAINED_CLAY"),
	LIGHT_GRAY_CONCRETE_POWDER(8, "CONCRETE_POWDER", "WOOL"),
	LIGHT_GRAY_DYE(7, "INK_SACK"),
	LIGHT_GRAY_GLAZED_TERRACOTTA(8, true, "SILVER_GLAZED_TERRACOTTA", "STAINED_CLAY"),
	LIGHT_GRAY_SHULKER_BOX(true, "CHEST"),
	LIGHT_GRAY_STAINED_GLASS(8, "STAINED_GLASS"),
	LIGHT_GRAY_STAINED_GLASS_PANE(8, "STAINED_GLASS_PANE"),
	LIGHT_GRAY_TERRACOTTA(8, "STAINED_CLAY"),
	LIGHT_GRAY_WALL_BANNER(7, "WALL_BANNER"),
	LIGHT_GRAY_WOOL(8, "WOOL"),
	LIGHT_WEIGHTED_PRESSURE_PLATE("GOLD_PLATE"),
	LIGHTNING_ROD(true, "ACACIA_FENCE"),
	LILAC(1, "DOUBLE_PLANT"),
	LILY_OF_THE_VALLEY(3, true, "AZURE_BLUET", "RED_ROSE"),
	LILY_PAD("WATER_LILY"),
	LIME_BANNER(10, "BANNER"),
	LIME_BED(5, "BED"),
	LIME_CANDLE(true, "TORCH"),
	LIME_CANDLE_CAKE(true, "CAKE"),
	LIME_CARPET(5, "CARPET"),
	LIME_CONCRETE(5, "CONCRETE", "STAINED_CLAY"),
	LIME_CONCRETE_POWDER(5, "CONCRETE_POWDER", "WOOL"),
	LIME_DYE(10, "INK_SACK"),
	LIME_GLAZED_TERRACOTTA(5, true, "STAINED_CLAY"),
	LIME_SHULKER_BOX(true, "CHEST"),
	LIME_STAINED_GLASS(5, "STAINED_GLASS"),
	LIME_STAINED_GLASS_PANE(5, "STAINED_GLASS_PANE"),
	LIME_TERRACOTTA(5, "STAINED_CLAY"),
	LIME_WALL_BANNER(10, "WALL_BANNER"),
	LIME_WOOL(5, "WOOL"),
	LINGERING_POTION(true, "POTION"),
	LLAMA_SPAWN_EGG(101, true, "MONSTER_EGG"),
	LODESTONE(8, true, "DOUBLE_STEP"),
	LOOM(true, "CRAFTING_TABLE", "WORKBENCH"),
	MAGENTA_BANNER(13, "BANNER"),
	MAGENTA_BED(2, "BED"),
	MAGENTA_CANDLE(true, "TORCH"),
	MAGENTA_CANDLE_CAKE(true, "CAKE"),
	MAGENTA_CARPET(2, "CARPET"),
	MAGENTA_CONCRETE(2, "CONCRETE", "STAINED_CLAY"),
	MAGENTA_CONCRETE_POWDER(2, "CONCRETE_POWDER", "WOOL"),
	MAGENTA_DYE(13, "INK_SACK"),
	MAGENTA_GLAZED_TERRACOTTA(2, true, "STAINED_CLAY"),
	MAGENTA_SHULKER_BOX(true, "CHEST"),
	MAGENTA_STAINED_GLASS(2, "STAINED_GLASS"),
	MAGENTA_STAINED_GLASS_PANE(2, "STAINED_GLASS_PANE"),
	MAGENTA_TERRACOTTA(2, "STAINED_CLAY"),
	MAGENTA_WALL_BANNER(13, "BANNER"),
	MAGENTA_WOOL(2, "WOOL"),
	MAGMA_BLOCK(true, "NETHERRACK"),
	MAGMA_CREAM,
	MAGMA_CUBE_SPAWN_EGG(62, "MONSTER_EGG"),
	MANGROVE_BOAT(true, "JUNGLE_BOAT", "BOAT"),
	MANGROVE_BUTTON(true, "JUNGLE_BUTTON", "WOOD_BUTTON"),
	MANGROVE_CHEST_BOAT(true, "JUNGLE_BOAT", "BOAT"),
	MANGROVE_DOOR(true, "JUNGLE_DOOR"),
	MANGROVE_FENCE(true, "JUNGLE_FENCE"),
	MANGROVE_FENCE_GATE(true, "JUNGLE_FENCE_GATE"),
	MANGROVE_HANGING_SIGN(true, "JUNGLE_SIGN", "SIGN"),
	MANGROVE_LEAVES(3, true, "JUNGLE_LEAVES", "LEAVES"),
	MANGROVE_LOG(3, true, "JUNGLE_LOG", "LOG"),
	MANGROVE_PLANKS(3, true, "JUNGLE_PLANKS", "WOOD"),
	MANGROVE_PRESSURE_PLATE(true, "JUNGLE_PRESSURE_PLATE", "WOOD_PLATE"),
	MANGROVE_PROPAGULE(3, true, "JUNGLE_SAPLING", "SAPLING"),
	MANGROVE_ROOTS(3, true, "JUNGLE_LEAVES", "LEAVES"),
	MANGROVE_SIGN(true, "JUNGLE_SIGN", "SIGN"),
	MANGROVE_SLAB(3, true, "JUNGLE_SLAB", "WOOD_STEP"),
	MANGROVE_STAIRS(true, "JUNGLE_STAIRS", "JUNGLE_WOOD_STAIRS"),
	MANGROVE_TRAPDOOR(true, "JUNGLE_TRAPDOOR", "TRAP_DOOR"),
	MANGROVE_WALL_HANGING_SIGN(true, "JUNGLE_WALL_SIGN", "WALL_SIGN"),
	MANGROVE_WALL_SIGN(true, "JUNGLE_WALL_SIGN", "WALL_SIGN"),
	MANGROVE_WOOD(15, true, "LOG"),
	MAP("EMPTY_MAP"),
	MEDIUM_AMETHYST_BUD(2, true, "ALLIUM", "RED_ROSE"),
	MELON("MELON_BLOCK"),
	MELON_SEEDS,
	MELON_SLICE("MELON"),
	MELON_STEM,
	MILK_BUCKET,
	MINECART,
	MINER_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	MOJANG_BANNER_PATTERN(true, "PAPER"),
	MOOSHROOM_SPAWN_EGG(96, "MONSTER_EGG"),
	MOSS_BLOCK(true, "GRASS_BLOCK", "LONG_GRASS"),
	MOSS_CARPET(13, true, "CARPET"),
	MOSSY_COBBLESTONE,
	MOSSY_COBBLESTONE_SLAB(3, true, "COBBLESTONE_SLAB", "STEP"),
	MOSSY_COBBLESTONE_STAIRS(true, "COBBLESTONE_STAIRS"),
	MOSSY_COBBLESTONE_WALL(1, true, "COBBLE_WALL"),
	MOSSY_STONE_BRICK_SLAB(5, "STONE_BRICK_SLAB", "STEP"),
	MOSSY_STONE_BRICK_STAIRS(true, "STONE_BRICK_STAIRS", "SMOOTH_STAIRS"),
	MOSSY_STONE_BRICK_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	MOSSY_STONE_BRICKS(1, "SMOOTH_BRICK"),
	MOURNER_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	MOVING_PISTON(3, "PISTON_BASE"),
	MUD(true, "DIRT"),
	MUD_BRICK_SLAB(4, true, "BRICK_SLAB", "STEP"),
	MUD_BRICK_STAIRS(true, "BRICK_STAIRS"),
	MUD_BRICK_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	MUD_BRICKS(true, "BRICKS", "BRICK"),
	MUDDY_MANGROVE_ROOTS(true, "SOUL_SAND"),
	MULE_SPAWN_EGG(100, true, "MONSTER_EGG"),
	MUSHROOM_STEM(15, "HUGE_MUSHROOM_2"),
	MUSHROOM_STEW("MUSHROOM_SOUP"),
	MUSIC_DISC_11("RECORD_11"),
	MUSIC_DISC_13("GOLD_RECORD"),
	MUSIC_DISC_5(true, "MUSIC_DISC_11", "RECORD_11"),
	MUSIC_DISC_BLOCKS("RECORD_3"),
	MUSIC_DISC_CAT("GREEN_RECORD"),
	MUSIC_DISC_CHIRP("RECORD_4"),
	MUSIC_DISC_FAR("RECORD_5"),
	MUSIC_DISC_MALL("RECORD_6"),
	MUSIC_DISC_MELLOHI("RECORD_7"),
	MUSIC_DISC_OTHERSIDE(true, "MUSIC_DISC_11", "RECORD_11"),
	MUSIC_DISC_PIGSTEP(true, "MUSIC_DISC_11", "RECORD_11"),
	MUSIC_DISC_RELIC(true, "MUSIC_DISC_11", "RECORD_11"),
	MUSIC_DISC_STAL("RECORD_8"),
	MUSIC_DISC_STRAD("RECORD_9"),
	MUSIC_DISC_WAIT("RECORD_12"),
	MUSIC_DISC_WARD("RECORD_10"),
	MUTTON,
	MYCELIUM("MYCEL"),
	NAME_TAG,
	NAUTILUS_SHELL(7, true, "INK_SACK"),
	NETHER_BRICK,
	NETHER_BRICK_FENCE("NETHER_FENCE"),
	NETHER_BRICK_SLAB(6, "STEP"),
	NETHER_BRICK_STAIRS,
	NETHER_BRICK_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	NETHER_BRICKS("NETHER_BRICK"),
	NETHER_GOLD_ORE(true, "GOLD_ORE"),
	NETHER_PORTAL(1, "PORTAL"),
	NETHER_QUARTZ_ORE("QUARTZ_ORE"),
	NETHER_SPROUTS(1, true, "GRASS_BLOCK", "LONG_GRASS"),
	NETHER_STAR,
	NETHER_WART("NETHER_STALK"),
	NETHER_WART_BLOCK(true, "NETHER_BRICK"),
	NETHERITE_AXE("DIAMOND_AXE"),
	NETHERITE_BLOCK("DIAMOND_BLOCK"),
	NETHERITE_BOOTS("DIAMOND_BOOTS"),
	NETHERITE_CHESTPLATE("DIAMOND_CHESTPLATE"),
	NETHERITE_HELMET("DIAMOND_HELMET"),
	NETHERITE_HOE("DIAMOND_HOE"),
	NETHERITE_INGOT("DIAMOND"),
	NETHERITE_LEGGINGS("DIAMOND_LEGGINGS"),
	NETHERITE_PICKAXE("DIAMOND_PICKAXE"),
	NETHERITE_SCRAP("DIAMOND"),
	NETHERITE_SHOVEL("DIAMOND_SPADE"),
	NETHERITE_SWORD("DIAMOND_SWORD"),
	NETHERITE_UPGRADE_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	NETHERRACK,
	NOTE_BLOCK,
	OAK_BOAT("BOAT"),
	OAK_BUTTON("WOOD_BUTTON"),
	OAK_CHEST_BOAT(true, "OAK_BOAT", "BOAT"),
	OAK_DOOR("WOOD_DOOR"),
	OAK_FENCE("FENCE"),
	OAK_FENCE_GATE("FENCE_GATE"),
	OAK_HANGING_SIGN(true, "OAK_SIGN", "SIGN"),
	OAK_LEAVES("LEAVES"),
	OAK_LOG("LOG"),
	OAK_PLANKS("WOOD"),
	OAK_PRESSURE_PLATE("WOOD_PLATE"),
	OAK_SAPLING("SAPLING"),
	OAK_SIGN("SIGN"),
	OAK_SLAB("WOOD_STEP"),
	OAK_STAIRS("WOOD_STAIRS"),
	OAK_TRAPDOOR("TRAP_DOOR"),
	OAK_WALL_HANGING_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	OAK_WALL_SIGN(true, "WALL_SIGN"),
	OAK_WOOD(12, "LOG"),
	OBSERVER("DISPENSER"),
	OBSIDIAN,
	OCELOT_SPAWN_EGG(98, "MONSTER_EGG"),
	OCHRE_FROGLIGHT(true, "SEA_LANTERN"),
	ORANGE_BANNER(14, "BANNER"),
	ORANGE_BED(1, "BED"),
	ORANGE_CANDLE(true, "TORCH"),
	ORANGE_CANDLE_CAKE(true, "CAKE"),
	ORANGE_CARPET(1, "CARPET"),
	ORANGE_CONCRETE(1, "CONCRETE", "STAINED_CLAY"),
	ORANGE_CONCRETE_POWDER(1, "CONCRETE_POWDER", "WOOL"),
	ORANGE_DYE(14, "INK_SACK"),
	ORANGE_GLAZED_TERRACOTTA(1, true, "STAINED_CLAY"),
	ORANGE_SHULKER_BOX(true, "CHEST"),
	ORANGE_STAINED_GLASS(1, "STAINED_GLASS"),
	ORANGE_STAINED_GLASS_PANE(1, "STAINED_GLASS_PANE"),
	ORANGE_TERRACOTTA(1, "STAINED_CLAY"),
	ORANGE_TULIP(5, "RED_ROSE"),
	ORANGE_WALL_BANNER(14, "WALL_BANNER"),
	ORANGE_WOOL(1, "WOOL"),
	OXEYE_DAISY(8, "RED_ROSE"),
	OXIDIZED_COPPER(1, true, "PRISMARINE_BRICKS", "PRISMARINE"),
	OXIDIZED_CUT_COPPER(1, true, "PRISMARINE_BRICKS", "PRISMARINE"),
	OXIDIZED_CUT_COPPER_SLAB(true, "PRISMARINE_BRICK_SLAB", "STEP"),
	OXIDIZED_CUT_COPPER_STAIRS(true, "PRISMARINE_BRICK_STAIRS", "COBBLESTONE_STAIRS"),
	PACKED_ICE,
	PACKED_MUD(1, true, "COARSE_DIRT", "DIRT"),
	PAINTING,
	PANDA_SPAWN_EGG(51, true, "SKELETON_SPAWN_EGG", "MONSTER_EGG"),
	PAPER,
	PARROT_SPAWN_EGG(50, true, "MONSTER_EGG"),
	PEARLESCENT_FROGLIGHT(true, "SEA_LANTERN"),
	PEONY(5, "DOUBLE_PLANT"),
	PETRIFIED_OAK_SLAB(true, "OAK_SLAB", "STEP"),
	PHANTOM_MEMBRANE(15, true, "INK_SACK"),
	PHANTOM_SPAWN_EGG(94, true, "MONSTER_EGG"),
	PIG_SPAWN_EGG(90, "MONSTER_EGG"),
	PIGLIN_BANNER_PATTERN(true, "PAPER"),
	PIGLIN_BRUTE_SPAWN_EGG(57, true, "ZOMBIE_PIGMAN_SPAWN_EGG", "MONSTER_EGG"),
	PIGLIN_HEAD(3, true, "PLAYER_HEAD", "SKULL"),
	PIGLIN_SPAWN_EGG(57, true, "ZOMBIE_PIGMAN_SPAWN_EGG", "MONSTER_EGG"),
	PIGLIN_WALL_HEAD(3, true, "PLAYER_HEAD", "SKULL"),
	PILLAGER_SPAWN_EGG(120, "VILLAGER_SPAWN_EGG", "MONSTER_EGG"),
	PINK_BANNER(9, "BANNER"),
	PINK_BED(6, "BED"),
	PINK_CANDLE(true, "TORCH"),
	PINK_CANDLE_CAKE(true, "CAKE"),
	PINK_CARPET(6, "CARPET"),
	PINK_CONCRETE(6, "CONCRETE", "STAINED_CLAY"),
	PINK_CONCRETE_POWDER(6, "CONCRETE_POWDER", "WOOL"),
	PINK_DYE(9, "INK_SACK"),
	PINK_GLAZED_TERRACOTTA(6, true, "STAINED_CLAY"),
	PINK_PETALS(7, true, "RED_ROSE"),
	PINK_SHULKER_BOX(true, "CHEST"),
	PINK_STAINED_GLASS(6, "STAINED_GLASS"),
	PINK_STAINED_GLASS_PANE(6, "STAINED_GLASS_PANE"),
	PINK_TERRACOTTA(6, "STAINED_CLAY"),
	PINK_TULIP(7, "RED_ROSE"),
	PINK_WALL_BANNER(9, "WALL_BANNER"),
	PINK_WOOL(6, "WOOL"),
	PISTON("PISTON_BASE"),
	PISTON_HEAD("PISTON_EXTENSION"),
	PITCHER_CROP(7, true, "MELON_STEM"),
	PITCHER_PLANT(5, true, "PEONY", "DOUBLE_PLANT"),
	PITCHER_POD(true, "FIRE_CHARGE", "FIREBALL"),
	PLAYER_HEAD(3, "SKULL"),
	PLAYER_WALL_HEAD(4, "SKULL"),
	PLENTY_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	PODZOL(2, "DIRT"),
	POINTED_DRIPSTONE(true, "IRON_FENCE"),
	POISONOUS_POTATO,
	POLAR_BEAR_SPAWN_EGG(56, true, "MONSTER_EGG"),
	POLISHED_ANDESITE(4, "STONE"),
	POLISHED_ANDESITE_SLAB(7, true, "STEP"),
	POLISHED_ANDESITE_STAIRS(true, "QUARTZ_STAIRS"),
	POLISHED_BASALT(true, "STONE"),
	POLISHED_BLACKSTONE(15, true, "BLACK_WOOL", "WOOL"),
	POLISHED_BLACKSTONE_BRICK_SLAB(5, true, "STONE_BRICK_SLAB", "STEP"),
	POLISHED_BLACKSTONE_BRICK_STAIRS(true, "STONE_BRICK_STAIRS", "SMOOTH_STAIRS"),
	POLISHED_BLACKSTONE_BRICK_WALL(true, "STONE_BRICK_WALL", "COBBLE_WALL"),
	POLISHED_BLACKSTONE_BRICKS(true, "STONE_BRICKS", "SMOOTH_BRICK"),
	POLISHED_BLACKSTONE_BUTTON(true, "STONE_BUTTON"),
	POLISHED_BLACKSTONE_PRESSURE_PLATE(true, "STONE_PRESSURE_PLATE", "STONE_PLATE"),
	POLISHED_BLACKSTONE_SLAB(true, "STONE_SLAB", "STEP"),
	POLISHED_BLACKSTONE_STAIRS(true, "COBBLESTONE_STAIRS"),
	POLISHED_BLACKSTONE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	POLISHED_DEEPSLATE(true, "COBBLESTONE"),
	POLISHED_DEEPSLATE_SLAB(3, true, "COBBLESTONE_SLAB", "STEP"),
	POLISHED_DEEPSLATE_STAIRS(true, "COBBLESTONE_STAIRS"),
	POLISHED_DEEPSLATE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	POLISHED_DIORITE(4, "STONE"),
	POLISHED_DIORITE_SLAB(7, true, "QUARTZ_SLAB", "STEP"),
	POLISHED_DIORITE_STAIRS(true, "QUARTZ_STAIRS"),
	POLISHED_GRANITE(2, "STONE"),
	POLISHED_GRANITE_SLAB(4, true, "BRICK_SLAB", "STEP"),
	POLISHED_GRANITE_STAIRS(true, "BRICK_STAIRS"),
	POPPED_CHORUS_FRUIT(2, "CHORUS_FRUIT_POPPED", "RED_ROSE"),
	POPPY("RED_ROSE"),
	PORKCHOP("PORK"),
	POTATO,
	POTATOES("POTATO"),
	POTION,
	POTTED_ACACIA_SAPLING(true, "FLOWER_POT"),
	POTTED_ALLIUM(true, "FLOWER_POT"),
	POTTED_AZALEA_BUSH(true, "FLOWER_POT"),
	POTTED_AZURE_BLUET(true, "FLOWER_POT"),
	POTTED_BAMBOO(true, "FLOWER_POT"),
	POTTED_BIRCH_SAPLING(true, "FLOWER_POT"),
	POTTED_BLUE_ORCHID(true, "FLOWER_POT"),
	POTTED_BROWN_MUSHROOM(true, "FLOWER_POT"),
	POTTED_CACTUS(true, "FLOWER_POT"),
	POTTED_CHERRY_SAPLING(true, "FLOWER_POT"),
	POTTED_CORNFLOWER(true, "FLOWER_POT"),
	POTTED_CRIMSON_FUNGUS(true, "FLOWER_POT"),
	POTTED_CRIMSON_ROOTS(true, "FLOWER_POT"),
	POTTED_DANDELION(true, "FLOWER_POT"),
	POTTED_DARK_OAK_SAPLING(true, "FLOWER_POT"),
	POTTED_DEAD_BUSH(true, "FLOWER_POT"),
	POTTED_FERN(true, "FLOWER_POT"),
	POTTED_FLOWERING_AZALEA_BUSH(true, "FLOWER_POT"),
	POTTED_JUNGLE_SAPLING(true, "FLOWER_POT"),
	POTTED_LILY_OF_THE_VALLEY(true, "FLOWER_POT"),
	POTTED_MANGROVE_PROPAGULE(true, "FLOWER_POT"),
	POTTED_OAK_SAPLING(true, "FLOWER_POT"),
	POTTED_ORANGE_TULIP(true, "FLOWER_POT"),
	POTTED_OXEYE_DAISY(true, "FLOWER_POT"),
	POTTED_PINK_TULIP(true, "FLOWER_POT"),
	POTTED_POPPY(true, "FLOWER_POT"),
	POTTED_RED_MUSHROOM(true, "FLOWER_POT"),
	POTTED_RED_TULIP(true, "FLOWER_POT"),
	POTTED_SPRUCE_SAPLING(true, "FLOWER_POT"),
	POTTED_TORCHFLOWER(true, "FLOWER_POT"),
	POTTED_WARPED_FUNGUS(true, "FLOWER_POT"),
	POTTED_WARPED_ROOTS(true, "FLOWER_POT"),
	POTTED_WHITE_TULIP(true, "FLOWER_POT"),
	POTTED_WITHER_ROSE(true, "FLOWER_POT"),
	POWDER_SNOW(true, "SNOW_BLOCK"),
	POWDER_SNOW_BUCKET(true, "WATER_BUCKET"),
	POWDER_SNOW_CAULDRON(3, true, "CAULDRON"),
	POWERED_RAIL,
	PRISMARINE,
	PRISMARINE_BRICK_SLAB(4, true, "BRICK_SLAB", "STEP"),
	PRISMARINE_BRICK_STAIRS(true, "BRICK_STAIRS"),
	PRISMARINE_BRICKS(1, "PRISMARINE"),
	PRISMARINE_CRYSTALS,
	PRISMARINE_SHARD,
	PRISMARINE_SLAB(3, true, "STEP"),
	PRISMARINE_STAIRS(true, "COBBLESTONE_STAIRS"),
	PRISMARINE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	PRIZE_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	PUFFERFISH(3, "RAW_FISH"),
	PUFFERFISH_BUCKET(true, "WATER_BUCKET"),
	PUFFERFISH_SPAWN_EGG(98, true, "MONSTER_EGG"),
	PUMPKIN,
	PUMPKIN_PIE,
	PUMPKIN_SEEDS,
	PUMPKIN_STEM,
	PURPLE_BANNER(5, "BANNER"),
	PURPLE_BED(10, "BED"),
	PURPLE_CANDLE(true, "TORCH"),
	PURPLE_CANDLE_CAKE(true, "CAKE"),
	PURPLE_CARPET(10, "CARPET"),
	PURPLE_CONCRETE(10, "CONCRETE", "STAINED_CLAY"),
	PURPLE_CONCRETE_POWDER(10, "CONCRETE_POWDER", "WOOL"),
	PURPLE_DYE(5, "INK_SACK"),
	PURPLE_GLAZED_TERRACOTTA(10, true, "STAINED_CLAY"),
	PURPLE_SHULKER_BOX(true, "CHEST"),
	PURPLE_STAINED_GLASS(10, "STAINED_GLASS"),
	PURPLE_STAINED_GLASS_PANE(10, "STAINED_GLASS_PANE"),
	PURPLE_TERRACOTTA(10, "STAINED_CLAY"),
	PURPLE_WALL_BANNER(5, "WALL_BANNER"),
	PURPLE_WOOL(10, "WOOL"),
	PURPUR_BLOCK(10, true, "WOOL"),
	PURPUR_PILLAR(2, true,"QUARTZ_BLOCK"),
	PURPUR_SLAB(7, true, "STEP"),
	PURPUR_STAIRS(true, "QUARTZ_STAIRS"),
	QUARTZ,
	QUARTZ_BLOCK,
	QUARTZ_BRICKS(true, "QUARTZ_BLOCK"),
	QUARTZ_PILLAR(2, "QUARTZ_BLOCK"),
	QUARTZ_SLAB(7, "STEP"),
	QUARTZ_STAIRS,
	RABBIT,
	RABBIT_FOOT,
	RABBIT_HIDE,
	RABBIT_SPAWN_EGG(101, "MONSTER_EGG"),
	RABBIT_STEW,
	RAIL("RAILS"),
	RAISER_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	RAVAGER_SPAWN_EGG(60, "MONSTER_EGG"),
	RAW_COPPER(true, "IRON_INGOT"),
	RAW_COPPER_BLOCK(true, "IRON_BLOCK"),
	RAW_GOLD(true, "GOLD_INGOT"),
	RAW_GOLD_BLOCK(true, "GOLD_BLOCK"),
	RAW_IRON(true, "IRON_INGOT"),
	RAW_IRON_BLOCK(true, "IRON_BLOCK"),
	RECOVERY_COMPASS(true, "COMPASS"),
	RED_BANNER(1, "BANNER"),
	RED_BED(14, "BED"),
	RED_CANDLE(true, "TORCH"),
	RED_CANDLE_CAKE(true, "CAKE"),
	RED_CARPET(14, "CARPET"),
	RED_CONCRETE(14, "CONCRETE", "STAINED_CLAY"),
	RED_CONCRETE_POWDER(14, "CONCRETE_POWDER", "WOOL"),
	RED_DYE(1, "INK_SACK"),
	RED_GLAZED_TERRACOTTA(14, true, "STAINED_CLAY"),
	RED_MUSHROOM,
	RED_MUSHROOM_BLOCK(14, "HUGE_MUSHROOM_2"),
	RED_NETHER_BRICK_SLAB(6, true, "NETHER_BRICK_SLAB", "STEP"),
	RED_NETHER_BRICK_STAIRS(true, "NETHER_BRICK_STAIRS"),
	RED_NETHER_BRICK_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	RED_NETHER_BRICKS(true, "NETHER_BRICK"),
	RED_SAND(1, "SAND"),
	RED_SANDSTONE,
	RED_SANDSTONE_SLAB("STONE_SLAB2"),
	RED_SANDSTONE_STAIRS,
	RED_SANDSTONE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	RED_SHULKER_BOX(true, "CHEST"),
	RED_STAINED_GLASS(14, "STAINED_GLASS"),
	RED_STAINED_GLASS_PANE(14, "STAINED_GLASS_PANE"),
	RED_TERRACOTTA(14, "STAINED_CLAY"),
	RED_TULIP(4, "RED_ROSE"),
	RED_WALL_BANNER(1, "WALL_BANNER"),
	RED_WOOL(14, "WOOL"),
	REDSTONE,
	REDSTONE_BLOCK,
	REDSTONE_LAMP("REDSTONE_LAMP_OFF", "REDSTONE_LAMP_ON"),
	REDSTONE_ORE,
	REDSTONE_TORCH("REDSTONE_TORCH_ON", "REDSTONE_TORCH_OFF"),
	REDSTONE_WALL_TORCH("REDSTONE_TORCH_ON", "REDSTONE_TORCH_OFF"),
	REDSTONE_WIRE,
	REINFORCED_DEEPSLATE(true, "OBSIDIAN"),
	REPEATER("DIODE"),
	REPEATING_COMMAND_BLOCK("COMMAND"),
	RESPAWN_ANCHOR(true, "OBSIDIAN"),
	RIB_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	ROOTED_DIRT(1, true, "DIRT"),
	ROSE_BUSH(4, "DOUBLE_PLANT"),
	ROTTEN_FLESH,
	SADDLE,
	SALMON(1, "RAW_FISH"),
	SALMON_BUCKET(true, "WATER_BUCKET"),
	SALMON_SPAWN_EGG(93, true, "MONSTER_EGG"),
	SAND,
	SANDSTONE,
	SANDSTONE_SLAB(1, "STEP"),
	SANDSTONE_STAIRS,
	SANDSTONE_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	SCAFFOLDING(true, "LADDER"),
	SCULK(9, true, "WOOL"),
	SCULK_CATALYST(9, true, "WOOL"),
	SCULK_SENSOR(9, true, "WOOL"),
	SCULK_SHRIEKER(9, true, "WOOL"),
	SCULK_VEIN(true, "VINE"),
	SEA_LANTERN,
	SEA_PICKLE(6, true, "RED_ROSE"),
	SEAGRASS(1, true, "LONG_GRASS"),
	SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	SHEAF_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	SHEARS,
	SHEEP_SPAWN_EGG(91, "MONSTER_EGG"),
	SHELTER_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	SHIELD(true, "IRON_SWORD"),
	SHROOMLIGHT(true, "GLOWSTONE"),
	SHORT_GRASS("LONG_GRASS"),
	SHULKER_BOX(true, "CHEST"),
	SHULKER_SHELL(9, true, "INK_SACK"),
	SHULKER_SPAWN_EGG(67, true, "MONSTER_EGG"),
	SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	SILVERFISH_SPAWN_EGG(60, "MONSTER_EGG"),
	SKELETON_HORSE_SPAWN_EGG(51, true, "MONSTER_EGG"),
	SKELETON_SKULL("SKULL"),
	SKELETON_SPAWN_EGG(51, true, "MONSTER_EGG"),
	SKELETON_WALL_SKULL("SKULL"),
	SKULL_BANNER_PATTERN(true, "PAPER"),
	SKULL_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	SLIME_BALL,
	SLIME_BLOCK,
	SLIME_SPAWN_EGG(55, "MONSTER_EGG"),
	SMALL_AMETHYST_BUD(true, "PRISMARINE_CRYSTALS"),
	SMALL_DRIPLEAF(2, true, "FERN", "LONG_GRASS"),
	SMITHING_TABLE(true, "CRAFTING_TABLE", "WORKBENCH"),
	SMOKER(true, "FURNACE"),
	SMOOTH_BASALT(7, true, "GRAY_WOOL", "WOOL"),
	SMOOTH_QUARTZ(true, "QUARTZ_BLOCK"),
	SMOOTH_QUARTZ_SLAB(7, true, "QUARTZ_SLAB", "STEP"),
	SMOOTH_QUARTZ_STAIRS(true, "QUARTZ_STAIRS"),
	SMOOTH_RED_SANDSTONE(true, "RED_SANDSTONE"),
	SMOOTH_RED_SANDSTONE_SLAB(true, "RED_SANDSTONE_SLAB", "STONE_SLAB2"),
	SMOOTH_RED_SANDSTONE_STAIRS(true, "RED_SANDSTONE_STAIRS"),
	SMOOTH_SANDSTONE(true, "SANDSTONE"),
	SMOOTH_SANDSTONE_SLAB(1, true, "SANDSTONE_SLAB", "STEP"),
	SMOOTH_SANDSTONE_STAIRS(true, "SANDSTONE_STAIRS"),
	SMOOTH_STONE(8, "DOUBLE_STEP"),
	SMOOTH_STONE_SLAB("STEP"),
	SNIFFER_EGG(true, "DRAGON_EGG"),
	SNIFFER_SPAWN_EGG(96, true, "MOOSHROOM_SPAWN_EGG", "MONSTER_EGG"),
	SNORT_POTTERY_SHERD(true, "BRICK", "CLAY_BRICK"),
	SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	SNOW,
	SNOW_BLOCK,
	SNOW_GOLEM_SPAWN_EGG(95, true, "MONSTER_EGG"),
	SNOWBALL("SNOW_BALL"),
	SOUL_CAMPFIRE(true, "CAMPFIRE", "FIRE"),
	SOUL_FIRE(true, "FIRE"),
	SOUL_LANTERN(true, "TORCH"),
	SOUL_SAND,
	SOUL_SOIL(true, "SOUL_SAND"),
	SOUL_TORCH(true, "TORCH"),
	SOUL_WALL_TORCH(5, true, "TORCH"),
	SPAWNER("MOB_SPAWNER"),
	SPECTRAL_ARROW(true, "ARROW"),
	SPIDER_EYE,
	SPIDER_SPAWN_EGG(52, "MONSTER_EGG"),
	SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	SPLASH_POTION(true, "POTION"),
	SPONGE,
	SPORE_BLOSSOM(1, true, "LILAC", "DOUBLE_PLANT"),
	SPRUCE_BOAT("BOAT_SPRUCE", "BOAT"),
	SPRUCE_BUTTON(true, "WOOD_BUTTON"),
	SPRUCE_CHEST_BOAT(true, "SPRUCE_BOAT", "BOAT_SPRUCE", "BOAT"),
	SPRUCE_DOOR,
	SPRUCE_FENCE,
	SPRUCE_FENCE_GATE,
	SPRUCE_HANGING_SIGN(true, "SPRUCE_SIGN", "SIGN"),
	SPRUCE_LEAVES(5, "LEAVES"),
	SPRUCE_LOG(1, "LOG"),
	SPRUCE_PLANKS(1, "WOOD"),
	SPRUCE_PRESSURE_PLATE(true, "WOOD_PLATE"),
	SPRUCE_SAPLING(1, "SAPLING"),
	SPRUCE_SIGN(true, "SIGN"),
	SPRUCE_SLAB(1, "WOOD_STEP"),
	SPRUCE_STAIRS("SPRUCE_WOOD_STAIRS"),
	SPRUCE_TRAPDOOR(true, "TRAP_DOOR"),
	SPRUCE_WALL_HANGING_SIGN(true, "SPRUCE_WALL_SIGN", "WALL_SIGN"),
	SPRUCE_WALL_SIGN(true, "SPRUCE_WALL_SIGN", "WALL_SIGN"),
	SPRUCE_WOOD(13, "LOG"),
	SPYGLASS(true, "COMPASS"),
	SQUID_SPAWN_EGG(94, "MONSTER_EGG"),
	STICK,
	STICKY_PISTON("PISTON_STICKY_BASE"),
	STONE,
	STONE_AXE,
	STONE_BRICK_SLAB(5, "STEP"),
	STONE_BRICK_STAIRS("SMOOTH_STAIRS"),
	STONE_BRICK_WALL(true, "COBBLESTONE_WALL", "COBBLE_WALL"),
	STONE_BRICKS("SMOOTH_BRICK"),
	STONE_BUTTON,
	STONE_HOE,
	STONE_PICKAXE,
	STONE_PRESSURE_PLATE("STONE_PLATE"),
	STONE_SHOVEL("STONE_SPADE"),
	STONE_SLAB("STEP"),
	STONE_STAIRS(true, "STONE_BRICK_STAIRS", "SMOOTH_STAIRS"),
	STONE_SWORD,
	STONECUTTER(true, "CRAFTING_TABLE", "WORKBENCH"),
	STRAY_SPAWN_EGG(94, true, "MONSTER_EGG"),
	STRIDER_SPAWN_EGG(52, true, "SPIDER_SPAWN_EGG", "MONSTER_EGG"),
	STRING,
	STRIPPED_ACACIA_LOG(true, "LOG_2"),
	STRIPPED_ACACIA_WOOD(true, "STRIPPED_ACACIA_LOG", "LOG_2"),
	STRIPPED_BAMBOO_BLOCK(true, "STRIPPED_OAK_LOG", "LOG"),
	STRIPPED_BIRCH_LOG(2, true, "LOG"),
	STRIPPED_BIRCH_WOOD(2, true, "STRIPPED_BIRCH_LOG", "LOG"),
	STRIPPED_CHERRY_LOG(3, true, "STRIPPED_JUNGLE_LOG", "LOG"),
	STRIPPED_CHERRY_WOOD(3, true, "STRIPPED_JUNGLE_LOG", "LOG"),
	STRIPPED_CRIMSON_HYPHAE(3, true, "STRIPPED_JUNGLE_LOG", "LOG"),
	STRIPPED_CRIMSON_STEM(3, true, "STRIPPED_JUNGLE_WOOD", "STRIPPED_JUNGLE_LOG", "LOG"),
	STRIPPED_DARK_OAK_LOG(1, true, "LOG_2"),
	STRIPPED_DARK_OAK_WOOD(1, true, "STRIPPED_DARK_OAK_LOG", "LOG_2"),
	STRIPPED_JUNGLE_LOG(3, true, "LOG"),
	STRIPPED_JUNGLE_WOOD(3, true, "STRIPPED_JUNGLE_LOG", "LOG"),
	STRIPPED_MANGROVE_LOG(3, true, "STRIPPED_CHERRY_LOG", "STRIPPED_JUNGLE_LOG", "LOG"),
	STRIPPED_MANGROVE_WOOD(3, true, "STRIPPED_CHERRY_WOOD", "STRIPPED_JUNGLE_WOOD", "STRIPPED_JUNGLE_LOG", "LOG"),
	STRIPPED_OAK_LOG(true, "LOG"),
	STRIPPED_OAK_WOOD(true, "STRIPPED_OAK_LOG", "LOG"),
	STRIPPED_SPRUCE_LOG(1, true, "LOG"),
	STRIPPED_SPRUCE_WOOD(1, true, "STRIPPED_SPRUCE_LOG", "LOG"),
	STRIPPED_WARPED_HYPHAE(2, true, "STRIPPED_BIRCH_LOG", "LOG"),
	STRIPPED_WARPED_STEM(2, true, "STRIPPED_BIRCH_WOOD", "STRIPPED_BIRCH_LOG", "LOG"),
	STRUCTURE_BLOCK(true, "BARRIER"),
	STRUCTURE_VOID(true, "BARRIER"),
	SUGAR,
	SUGAR_CANE,
	SUNFLOWER("DOUBLE_PLANT"),
	SUSPICIOUS_GRAVEL("GRAVEL"),
	SUSPICIOUS_SAND("SAND"),
	SUSPICIOUS_STEW(true, "MUSHROOM_SOUP"),
	SWEET_BERRIES(true, "MELON_SLICE", "MELON"),
	SWEET_BERRY_BUSH(4, true, "ROSE_BUSH", "DOUBLE_PLANT"),
	TADPOLE_BUCKET("WATER_BUCKET"),
	TADPOLE_SPAWN_EGG(65, "BAT_SPAWN_EGG", "MONSTER_EGG"),
	TALL_GRASS(2, "DOUBLE_PLANT"),
	TALL_SEAGRASS(2, true, "DOUBLE_PLANT"),
	TARGET(true, "REDSTONE_BLOCK"),
	TERRACOTTA("HARD_CLAY"),
	TIDE_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	TINTED_GLASS("HARD_CLAY"),
	TIPPED_ARROW(true, "ARROW"),
	TNT,
	TNT_MINECART("EXPLOSIVE_MINECART"),
	TORCH,
	TORCHFLOWER(1, true, "LILAC", "DOUBLE_PLANT"),
	TORCHFLOWER_CROP(1, true, "LILAC", "DOUBLE_PLANT"),
	TORCHFLOWER_SEEDS(true, "WHEAT_SEEDS", "SEEDS"),
	TOTEM_OF_UNDYING("TOTEM", "GOLD_INGOT"), //@GOLD_INGOT for 1.8
	TRADER_LLAMA_SPAWN_EGG(101, true, "MONSTER_EGG"),
	TRAPPED_CHEST,
	TRIDENT(true, "DIAMOND_SWORD"),
	TRIPWIRE(true, "DIAMOND_SWORD"),
	TRIPWIRE_HOOK,
	TROPICAL_FISH(2, "RAW_FISH"),
	TROPICAL_FISH_BUCKET(true, "WATER_BUCKET"),
	TROPICAL_FISH_SPAWN_EGG(101, true, "MONSTER_EGG"),
	TUBE_CORAL(1, true, "RED_ROSE"),
	TUBE_CORAL_BLOCK(true, "LAPIS_BLOCK"),
	TUBE_CORAL_FAN(1, true, "RED_ROSE"),
	TUBE_CORAL_WALL_FAN(1, true, "RED_ROSE"),
	TUFF(8, true, "LIGHT_GRAY_WOOL", "WOOL"),
	TURTLE_EGG(true, "EGG"),
	TURTLE_SCUTE(true, "SCUTE", "FEATHER"),
	TURTLE_HELMET(true, "LEATHER_HELMET"),
	TURTLE_SPAWN_EGG(56, true, "MONSTER_EGG"),
	TWISTING_VINES(true, "VINE"),
	TWISTING_VINES_PLANT(true, "VINE"),
	VERDANT_FROGLIGHT(true, "SEA_LANTERN"),
	VEX_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	VEX_SPAWN_EGG(105, true, "MONSTER_EGG"),
	VILLAGER_SPAWN_EGG(120, "MONSTER_EGG"),
	VINDICATOR_SPAWN_EGG(57, true, "MONSTER_EGG"),
	VINE,
	VOID_AIR(true, "AIR"),
	WALL_TORCH(5, "TORCH"),
	WANDERING_TRADER_SPAWN_EGG(120, true, "VILLAGER_SPAWN_EGG", "MONSTER_EGG"),
	WARD_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	WARDEN_SPAWN_EGG(94, true, "MONSTER_EGG"),
	WARPED_BUTTON(true, "OAK_BUTTON", "WOOD_BUTTON"),
	WARPED_DOOR(true, "OAK_DOOR", "WOODEN_DOOR"),
	WARPED_FENCE(true, "OAK_FENCE", "FENCE"),
	WARPED_FENCE_GATE(true, "OAK_FENCE_GATE", "FENCE_GATE"),
	WARPED_FUNGUS(true, "RED_MUSHROOM"),
	WARPED_FUNGUS_ON_A_STICK(true, "CARROT_ON_A_STICK", "CARROT_STICK"),
	WARPED_HANGING_SIGN(true, "OAK_SIGN", "SIGN"),
	WARPED_HYPHAE(12, true, "LOG"),
	WARPED_NYLIUM(true, "NETHERRACK"),
	WARPED_PLANKS(true, "OAK_PLANKS", "WOOD"),
	WARPED_PRESSURE_PLATE(true, "OAK_PRESSURE_PLATE", "WOOD_PLATE"),
	WARPED_ROOTS(1, true, "LONG_GRASS"),
	WARPED_SIGN(true, "OAK_SIGN", "SIGN"),
	WARPED_SLAB(true, "OAK_SLAB", "WOOD_STEP"),
	WARPED_STAIRS(true, "OAK_STAIRS", "WOOD_STAIRS"),
	WARPED_STEM(true, "OAK_LOG", "LOG"),
	WARPED_TRAPDOOR(true, "OAK_TRAPDOOR", "TRAP_DOOR"),
	WARPED_WALL_HANGING_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	WARPED_WALL_SIGN(true, "OAK_WALL_SIGN", "WALL_SIGN"),
	WARPED_WART_BLOCK(9, true, "CYAN_WOOL", "WOOL"),
	WATER,
	WATER_BUCKET,
	WATER_CAULDRON(3, "CAULDRON"),
	WAXED_COPPER_BLOCK(true, "RED_SANDSTONE"),
	WAXED_CUT_COPPER(1, true, "CHISELED_RED_SANDSTONE", "RED_SANDSTONE"),
	WAXED_CUT_COPPER_SLAB(true, "RED_SANDSTONE_SLAB", "STONE_SLAB2"),
	WAXED_CUT_COPPER_STAIRS(true, "RED_SANDSTONE_STAIRS"),
	WAXED_EXPOSED_COPPER(true, "RED_SANDSTONE"),
	WAXED_EXPOSED_CUT_COPPER(1, true, "CHISELED_RED_SANDSTONE", "RED_SANDSTONE"),
	WAXED_EXPOSED_CUT_COPPER_SLAB(true, "RED_SANDSTONE_SLAB", "STONE_SLAB2"),
	WAXED_EXPOSED_CUT_COPPER_STAIRS(true, "RED_SANDSTONE_STAIRS"),
	WAXED_OXIDIZED_COPPER(1, true, "PRISMARINE_BRICKS", "PRISMARINE"),
	WAXED_OXIDIZED_CUT_COPPER(1, true, "PRISMARINE_BRICKS", "PRISMARINE"),
	WAXED_OXIDIZED_CUT_COPPER_SLAB("SMOOTH_STONE_SLAB", "STEP"),
	WAXED_OXIDIZED_CUT_COPPER_STAIRS(true, "BIRCH_STAIRS", "BIRCH_WOOD_STAIRS"),
	WAXED_WEATHERED_COPPER(1, true, "PRISMARINE_BRICKS", "PRISMARINE"),
	WAXED_WEATHERED_CUT_COPPER(1, true, "PRISMARINE_BRICKS", "PRISMARINE"),
	WAXED_WEATHERED_CUT_COPPER_SLAB("SMOOTH_STONE_SLAB", "STEP"),
	WAXED_WEATHERED_CUT_COPPER_STAIRS(true, "BIRCH_STAIRS", "BIRCH_WOOD_STAIRS"),
	WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	WEATHERED_COPPER(1, true, "PRISMARINE_BRICKS", "PRISMARINE"),
	WEATHERED_CUT_COPPER(1, true, "PRISMARINE_BRICKS", "PRISMARINE"),
	WEATHERED_CUT_COPPER_SLAB("SMOOTH_STONE_SLAB", "STEP"),
	WEATHERED_CUT_COPPER_STAIRS(true, "BIRCH_STAIRS", "BIRCH_WOOD_STAIRS"),
	WEEPING_VINES(true, "VINE"),
	WEEPING_VINES_PLANT(true, "VINE"),
	WET_SPONGE(1, "SPONGE"),
	WHEAT,
	WHEAT_SEEDS("SEEDS"),
	WHITE_BANNER(15, "BANNER"),
	WHITE_BED("BED"),
	WHITE_CANDLE(true, "TORCH"),
	WHITE_CANDLE_CAKE(true, "CAKE"),
	WHITE_CARPET("CARPET"),
	WHITE_CONCRETE("CONCRETE", "STAINED_CLAY"),
	WHITE_CONCRETE_POWDER("CONCRETE_POWDER", "WOOL"),
	WHITE_DYE(15, true, "INK_SACK"),
	WHITE_GLAZED_TERRACOTTA(true, "STAINED_CLAY"),
	WHITE_SHULKER_BOX(true, "CHEST"),
	WHITE_STAINED_GLASS("STAINED_GLASS"),
	WHITE_STAINED_GLASS_PANE("STAINED_GLASS_PANE"),
	WHITE_TERRACOTTA("STAINED_CLAY"),
	WHITE_TULIP(6, "RED_ROSE"),
	WHITE_WALL_BANNER(15, "WALL_BANNER"),
	WHITE_WOOL("WOOL"),
	WILD_ARMOR_TRIM_SMITHING_TEMPLATE(true, "MUSIC_DISC_CHIRP", "RECORD_4"),
	WITCH_SPAWN_EGG(66, "MONSTER_EGG"),
	WITHER_ROSE(true, "RED_ROSE"),
	WITHER_SKELETON_SKULL(1, "SKULL"),
	WITHER_SKELETON_SPAWN_EGG(67, true, "MONSTER_EGG"),
	WITHER_SKELETON_WALL_SKULL(4, "SKULL"),
	WITHER_SPAWN_EGG(67, true, "MONSTER_EGG"),
	WOLF_SPAWN_EGG(95, "MONSTER_EGG"),
	WOODEN_AXE("WOOD_AXE"),
	WOODEN_HOE("WOOD_HOE"),
	WOODEN_PICKAXE("WOOD_PICKAXE"),
	WOODEN_SHOVEL("WOOD_SPADE"),
	WOODEN_SWORD("WOOD_SWORD"),
	WRITABLE_BOOK("BOOK_AND_QUILL"),
	WRITTEN_BOOK,
	YELLOW_BANNER(11, "BANNER"),
	YELLOW_BED(4, "BED"),
	YELLOW_CANDLE(true, "TORCH"),
	YELLOW_CANDLE_CAKE(true, "CAKE"),
	YELLOW_CARPET(4, "CARPET"),
	YELLOW_CONCRETE(4, "CONCRETE", "STAINED_CLAY"),
	YELLOW_CONCRETE_POWDER(4, "CONCRETE_POWDER", "WOOL"),
	YELLOW_DYE(11, "INK_SACK"),
	YELLOW_GLAZED_TERRACOTTA(4, true, "STAINED_CLAY"),
	YELLOW_SHULKER_BOX(true, "CHEST"),
	YELLOW_STAINED_GLASS(4, "STAINED_GLASS"),
	YELLOW_STAINED_GLASS_PANE(4, "STAINED_GLASS_PANE"),
	YELLOW_TERRACOTTA(4, "STAINED_CLAY"),
	YELLOW_WALL_BANNER(11, "WALL_BANNER"),
	YELLOW_WOOL(4, "WOOL"),
	ZOGLIN_SPAWN_EGG(101, true, "MONSTER_EGG"),
	ZOMBIE_HEAD(2, "SKULL"),
	ZOMBIE_HORSE_SPAWN_EGG(54, true, "MONSTER_EGG"),
	ZOMBIE_SPAWN_EGG(54, "MONSTER_EGG"),
	ZOMBIE_VILLAGER_SPAWN_EGG(54, true, "MONSTER_EGG"),
	ZOMBIE_WALL_HEAD(2, "SKULL"),
	ZOMBIFIED_PIGLIN_SPAWN_EGG(57, "MONSTER_EGG"),
	
	//1.20.5
	ARMODILLO_SPAWN_EGG(CHICKEN_SPAWN_EGG),
	ARMODILLO_SCUTE(TURTLE_SCUTE),
	WOLF_ARMOR(true, "LEATHER"),
	
	
	//1.21
	CHISELED_COPPER(CUT_COPPER),
	EXPOSED_CHISELED_COPPER(EXPOSED_CUT_COPPER),
    WEATHERED_CHISELED_COPPER(WEATHERED_CUT_COPPER),
    OXIDIZED_CHISELED_COPPER(OXIDIZED_CUT_COPPER),
    WAXED_CHISELED_COPPER(WAXED_CUT_COPPER),
    WAXED_EXPOSED_CHISELED_COPPER(WAXED_EXPOSED_CUT_COPPER),
    WAXED_WEATHERED_CHISELED_COPPER(WAXED_WEATHERED_CUT_COPPER),
    WAXED_OXIDIZED_CHISELED_COPPER(WAXED_OXIDIZED_CUT_COPPER),
    COPPER_DOOR(true, "IRON_DOOR"),
    EXPOSED_COPPER_DOOR(true, "IRON_DOOR"),
    WEATHERED_COPPER_DOOR(true, "IRON_DOOR"),
    OXIDIZED_COPPER_DOOR(true, "IRON_DOOR"),
    WAXED_COPPER_DOOR(true, "IRON_DOOR"),
    WAXED_EXPOSED_COPPER_DOOR(true, "IRON_DOOR"),
    WAXED_WEATHERED_COPPER_DOOR(true, "IRON_DOOR"),
    WAXED_OXIDIZED_COPPER_DOOR(true, "IRON_DOOR"),
    COPPER_TRAPDOOR(true, "IRON_TRAPDOOR"),
    EXPOSED_COPPER_TRAPDOOR(true, "IRON_TRAPDOOR"),
    WEATHERED_COPPER_TRAPDOOR(true, "IRON_TRAPDOOR"),
    OXIDIZED_COPPER_TRAPDOOR(true, "IRON_TRAPDOOR"),
    WAXED_COPPER_TRAPDOOR(true, "IRON_TRAPDOOR"),
    WAXED_EXPOSED_COPPER_TRAPDOOR(true, "IRON_TRAPDOOR"),
    WAXED_WEATHERED_COPPER_TRAPDOOR(true, "IRON_TRAPDOOR"),
    WAXED_OXIDIZED_COPPER_TRAPDOOR(true, "IRON_TRAPDOOR"),
    TUFF_SLAB(STONE_SLAB),
    TUFF_STAIRS(STONE_STAIRS),
    TUFF_WALL(STONE_BRICK_WALL),
    CHISELED_TUFF(STONE_BRICKS),
    POLISHED_TUFF(POLISHED_ANDESITE),
    POLISHED_TUFF_SLAB(POLISHED_ANDESITE_SLAB),
    POLISHED_TUFF_STAIRS(POLISHED_ANDESITE_STAIRS),
    POLISHED_TUFF_WALL(STONE_BRICK_WALL),
    TUFF_BRICK(STONE_BRICKS),
    TUFF_BRICK_SLAB(STONE_BRICK_SLAB),
    TUFF_BRICK_STAIRS(STONE_BRICK_STAIRS),
    TUFF_BRICK_WALL(STONE_BRICK_WALL),
    CHISELED_TUFF_BRICKS(CHISELED_STONE_BRICKS),
    CRAFTER(CRAFTING_TABLE),
	COPPER_GRATE(COPPER_BLOCK),
    EXPOSED_COPPER_GRATE(EXPOSED_COPPER),
    WEATHERED_COPPER_GRATE(WEATHERED_COPPER),
    OXIDIZED_COPPER_GRATE(OXIDIZED_COPPER),
    WAXED_COPPER_GRATE(WAXED_COPPER_BLOCK),
    WAXED_EXPOSED_COPPER_GRATE(WAXED_EXPOSED_COPPER),
    WAXED_WEATHERED_COPPER_GRATE(WAXED_WEATHERED_COPPER),
    WAXED_OXIDIZED_COPPER_GRATE(WAXED_OXIDIZED_COPPER),
    COPPER_BULB(REDSTONE_LAMP),
    EXPOSED_COPPER_BULB(REDSTONE_LAMP),
    WEATHERED_COPPER_BULB(REDSTONE_LAMP),
    OXIDIZED_COPPER_BULB(REDSTONE_LAMP),
    WAXED_COPPER_BULB(REDSTONE_LAMP),
    WAXED_EXPOSED_COPPER_BULB(REDSTONE_LAMP),
    WAXED_WEATHERED_COPPER_BULB(REDSTONE_LAMP),
    WAXED_OXIDIZED_COPPER_BULB(REDSTONE_LAMP),
    TRIAL_SPAWNER(SPAWNER),
    TRIAL_KEY(TRIPWIRE_HOOK),
    OMINOUS_TRIAL_KEY(TRIPWIRE_HOOK),
    VAULT(CHEST),
    OMINOUS_BOTTLE(GLASS_BOTTLE),
    BREEZE_ROD(BLAZE_ROD),
    HEAVY_CORE(PLAYER_HEAD),
	MACE(true, "DIAMOND_SWORD"),
	WIND_CHARGE(SNOWBALL),
	FLOW_ARMOR_TRIM_SMITHING_TEMPLATE(EYE_ARMOR_TRIM_SMITHING_TEMPLATE),
    BOLT_ARMOR_TRIM_SMITHING_TEMPLATE(WARD_ARMOR_TRIM_SMITHING_TEMPLATE),
    FLOW_POTTERY_SHERD(ANGLER_POTTERY_SHERD),
    GUSTER_POTTERY_SHERD(BLADE_POTTERY_SHERD),
    SCRAPE_POTTERY_SHERD(BURN_POTTERY_SHERD),
    FLOW_BANNER_PATTERN(FLOWER_BANNER_PATTERN),
    GUSTER_BANNER_PATTERN(CREEPER_BANNER_PATTERN),
    BREEZE_SPAWN_EGG(BLAZE_SPAWN_EGG),
    BOGGED_SPAWN_EGG(SKELETON_SPAWN_EGG),
    MUSIC_DISC_PRECIPICE(MUSIC_DISC_MELLOHI),
    MUSIC_DISC_CREATOR(MUSIC_DISC_PIGSTEP),
    MUSIC_DISC_CREATOR_MUSIC_BOX(MUSIC_DISC_PIGSTEP),
    
    //1.21.2
    GREEN_BUNDLE(BUNDLE),
	RED_BUNDLE(BUNDLE),
	LIME_BUNDLE(BUNDLE),
	YELLOW_BUNDLE(BUNDLE),
	LIGHT_BLUE_BUNDLE(BUNDLE),
	BLUE_BUNDLE(BUNDLE),
	PINK_BUNDLE(BUNDLE),
	ORANGE_BUNDLE(BUNDLE),
	WHITE_BUNDLE(BUNDLE),
	BROWN_BUNDLE(BUNDLE),
	BLACK_BUNDLE(BUNDLE),
	LIGHT_GRAY_BUNDLE(BUNDLE),
	GRAY_BUNDLE(BUNDLE),
	CYAN_BUNDLE(BUNDLE),
	MAGENTA_BUNDLE(BUNDLE),
	PURPLE_BUNDLE(BUNDLE),
	FIELD_MASONED_BANNER_PATTERN(CREEPER_BANNER_PATTERN),
	BORDURE_INDENTED_BANNER_PATTERN(FLOWER_BANNER_PATTERN),
	
	//1.21.4
	CREAKING_HEART(OAK_LOG),
	CHISELED_RESIN_BRICKS(CUT_COPPER),
    CREAKING_SPAWN_EGG(GUARDIAN_SPAWN_EGG),
	PALE_OAK_LOG(OAK_LOG),
	STRIPPED_PALE_OAK_LOG(STRIPPED_OAK_LOG),
	PALE_OAK_WOOD(OAK_WOOD),
	STRIPPED_PALE_OAK_WOOD(STRIPPED_OAK_WOOD),
    PALE_OAK_PLANKS(OAK_PLANKS),
    PALE_OAK_STAIRS(OAK_STAIRS),
    PALE_OAK_SLAB(OAK_SLAB),
    PALE_OAK_SIGN(OAK_SIGN),
    PALE_OAK_HANGING_SIGN(OAK_HANGING_SIGN),
    PALE_OAK_BUTTON(OAK_BUTTON),
    PALE_OAK_PRESSURE_PLATE(OAK_PRESSURE_PLATE),
    PALE_OAK_DOOR(OAK_DOOR),
    PALE_OAK_FENCE(OAK_FENCE),
    PALE_OAK_FENCE_GATE(OAK_FENCE_GATE),
    PALE_OAK_TRAPDOOR(OAK_TRAPDOOR),
    PALE_OAK_BOAT(OAK_BOAT),
    PALE_OAK_CHEST_BOAT(OAK_CHEST_BOAT),
    PALE_HANGING_MOSS(TALL_GRASS),
    PALE_MOSS_BLOCK(MOSS_BLOCK),
    PALE_MOSS_CARPET(MOSS_CARPET),
    PALE_OAK_LEAVES(OAK_LEAVES),
    PALE_OAK_SAPLING(OAK_SAPLING),
    CLOSED_EYEBLOSSOM(WITHER_ROSE),
    OPEN_EYEBLOSSOM(OXEYE_DAISY),
    RESIN_BLOCK(COPPER_BLOCK),
    RESIN_BRICK(COPPER_INGOT),
    RESIN_BRICK_SLAB(CUT_COPPER_SLAB),
    RESIN_BRICK_STAIRS(CUT_COPPER_STAIRS),
    RESIN_BRICK_WALL(RED_SANDSTONE_WALL),
    RESIN_BRICKS(CUT_COPPER),
    RESIN_CLUMP(RAW_COPPER),
	
	//1.21.5
	LEAF_LITTER(PINK_PETALS),
	WILDFLOWERS(PINK_PETALS),
	TEST_INSTANCE_BLOCK(COMMAND_BLOCK),
	TEST_BLOCK(COMMAND_BLOCK),
	BUSH(SHORT_GRASS),
	FIREFLY_BUSH(SHORT_GRASS),
	CACTUS_FLOWER(BRAIN_CORAL_FAN),
	SHORT_DRY_GRASS(SHORT_GRASS),
	TALL_DRY_GRASS(TALL_GRASS),
	BROWN_EGG(EGG),
	BLUE_EGG(EGG),
	
	//1.21.6
	DRIED_GHAST(WHITE_WOOL),
	WHITE_HARNESS(WHITE_CANDLE),
    ORANGE_HARNESS(ORANGE_CANDLE),
    MAGENTA_HARNESS(MAGENTA_CANDLE),
    LIGHT_BLUE_HARNESS(LIGHT_BLUE_CANDLE),
    YELLOW_HARNESS(YELLOW_CANDLE),
    LIME_HARNESS(LIME_CANDLE),
    PINK_HARNESS(PINK_CANDLE),
    GRAY_HARNESS(GRAY_CANDLE),
    LIGHT_GRAY_HARNESS(LIGHT_GRAY_CANDLE),
    CYAN_HARNESS(CYAN_CANDLE),
    PURPLE_HARNESS(PURPLE_CANDLE),
    BLUE_HARNESS(BLUE_CANDLE),
    BROWN_HARNESS(BROWN_CANDLE),
    GREEN_HARNESS(GREEN_CANDLE),
    RED_HARNESS(RED_CANDLE),
    BLACK_HARNESS(BLACK_CANDLE),
    HAPPY_GHAST_SPAWN_EGG(WOLF_SPAWN_EGG),
    MUSIC_DISC_TEARS(MUSIC_DISC_5),
    
    //1.21.7
    MUSIC_DISC_LAVA_CHICKEN(MUSIC_DISC_CHIRP),
	
	//1.21.9
	COPPER_CHEST(CHEST),
	EXPOSED_COPPER_CHEST(CHEST),
	WEATHERED_COPPER_CHEST(CHEST),
	OXIDIZED_COPPER_CHEST(CHEST),
	WAXED_COPPER_CHEST(CHEST),
	WAXED_EXPOSED_COPPER_CHEST(CHEST),
	WAXED_WEATHERED_COPPER_CHEST(CHEST),
	WAXED_OXIDIZED_COPPER_CHEST(CHEST),
	OAK_SHELF(BOOKSHELF),
	BIRCH_SHELF(BOOKSHELF),
	SPRUCE_SHELF(BOOKSHELF),
	JUNGLE_SHELF(BOOKSHELF),
	ACACIA_SHELF(BOOKSHELF),
	DARK_OAK_SHELF(BOOKSHELF),
	CRIMSON_SHELF(BOOKSHELF),
	WARPED_SHELF(BOOKSHELF),
	MANGROVE_SHELF(BOOKSHELF),
	BAMBOO_SHELF(BOOKSHELF),
	CHERRY_SHELF(BOOKSHELF),
	PALE_OAK_SHELF(BOOKSHELF),
	COPPER_GOLEM_STATUE(CUT_COPPER),
	EXPOSED_COPPER_GOLEM_STATUE(EXPOSED_CUT_COPPER),
	WEATHERED_COPPER_GOLEM_STATUE(WEATHERED_CUT_COPPER),
	OXIDIZED_COPPER_GOLEM_STATUE(OXIDIZED_CUT_COPPER),
	WAXED_COPPER_GOLEM_STATUE(WAXED_CUT_COPPER),
	WAXED_EXPOSED_COPPER_GOLEM_STATUE(WAXED_EXPOSED_CUT_COPPER),
	WAXED_WEATHERED_COPPER_GOLEM_STATUE(WAXED_WEATHERED_CUT_COPPER),
	WAXED_OXIDIZED_COPPER_GOLEM_STATUE(WAXED_OXIDIZED_CUT_COPPER),
	EXPOSED_LIGHTNING_ROD(LIGHTNING_ROD),
	WEATHERED_LIGHTNING_ROD(LIGHTNING_ROD),
	OXIDIZED_LIGHTNING_ROD(LIGHTNING_ROD),
	WAXED_LIGHTNING_ROD(LIGHTNING_ROD),
	WAXED_EXPOSED_LIGHTNING_ROD(LIGHTNING_ROD),
	WAXED_WEATHERED_LIGHTNING_ROD(LIGHTNING_ROD),
	WAXED_OXIDIZED_LIGHTNING_ROD(LIGHTNING_ROD),
	COPPER_GOLEM_SPAWN_EGG(IRON_GOLEM_SPAWN_EGG),
	COPPER_SWORD(IRON_SWORD),
	COPPER_AXE(IRON_AXE),
	COPPER_PICKAXE(IRON_PICKAXE),
	COPPER_SHOVEL(IRON_SHOVEL),
	COPPER_HOE(IRON_HOE),
	COPPER_HELMET(IRON_HELMET),
	COPPER_CHESTPLATE(IRON_CHESTPLATE),
	COPPER_LEGGINGS(IRON_LEGGINGS),
	COPPER_BOOTS(IRON_BOOTS),
	COPPER_HORSE_ARMOR(IRON_HORSE_ARMOR),
	COPPER_NUGGET(IRON_NUGGET),
	COPPER_TORCH(TORCH),
	COPPER_LANTERN(LANTERN),
	EXPOSED_COPPER_LANTERN(LANTERN),
	WEATHERED_COPPER_LANTERN(LANTERN),
	OXIDIZED_COPPER_LANTERN(LANTERN),
	WAXED_COPPER_LANTERN(LANTERN),
	WAXED_EXPOSED_COPPER_LANTERN(LANTERN),
	WAXED_WEATHERED_COPPER_LANTERN(LANTERN),
	WAXED_OXIDIZED_COPPER_LANTERN(LANTERN),
	COPPER_BARS(IRON_BARS),
	EXPOSED_COPPER_BARS(IRON_BARS),
	WEATHERED_COPPER_BARS(IRON_BARS),
	OXIDIZED_COPPER_BARS(IRON_BARS),
	WAXED_COPPER_BARS(IRON_BARS),
	WAXED_EXPOSED_COPPER_BARS(IRON_BARS),
	WAXED_WEATHERED_COPPER_BARS(IRON_BARS),
	WAXED_OXIDIZED_COPPER_BARS(IRON_BARS),
	COPPER_CHAIN(CHAIN),
	EXPOSED_COPPER_CHAIN(CHAIN),
	WEATHERED_COPPER_CHAIN(CHAIN),
	OXIDIZED_COPPER_CHAIN(CHAIN),
	WAXED_COPPER_CHAIN(CHAIN),
	WAXED_EXPOSED_COPPER_CHAIN(CHAIN),
	WAXED_WEATHERED_COPPER_CHAIN(CHAIN),
	WAXED_OXIDIZED_COPPER_CHAIN(CHAIN);
	
	private static final CoreMaterial[] VALUES = CoreMaterial.values();
    private static final Map<String, CoreMaterial> CORE_MATERIAL_MAPPINGS = JHelper.createImmutableMapFromArray(false, VALUES);
	
	private final byte legacyData;
	private final boolean customTranslation;
	private final String[] reflectedValues;
	
	@Nullable
	private final CoreMaterial linkedValue;
	
	private Material asBukkitMaterial;
	private ItemStack asBukkitItemStack;
	private boolean blockState;
	private boolean legacyItemSuffix;
	
	private CoreMaterial(int legacyData, boolean customTranslation, @Nullable CoreMaterial linkedValue, String... reflectedValues) {
		this.reflectedValues = reflectedValues;
		this.legacyData = (byte) legacyData;
		this.customTranslation = customTranslation;
		this.linkedValue = linkedValue;
	}
	
	private CoreMaterial() {
		this(0, false);
	}
	
	private CoreMaterial(CoreMaterial linkedValue) {
		this(0, false, linkedValue);
	}
	
	private CoreMaterial(String... reflectedValues) {
		this(0, false, reflectedValues);
	}

	private CoreMaterial(int legacyData, String... reflectedValues) {
		this(legacyData, false, reflectedValues);
	}
	
	private CoreMaterial(boolean customTranslation, String... reflectedValues) {
		this(0, customTranslation, reflectedValues);
	}
	
	private CoreMaterial(int legacyData, boolean customTranslation, String... reflectedValues) {
		this(legacyData, customTranslation, null, reflectedValues);
	}

	public String[] getReflectedValues() {
		return this.reflectedValues;
	}
	
	public byte getLegacyID() {
		return (byte) this.legacyData;
	}

	public boolean hasCustomTranslation() {
		return customTranslation;
	}
	
	@Nullable
	public CoreMaterial getLinkedValue() {
		return this.linkedValue;
	}
	
	@Deprecated
	public MaterialData toMaterialData() {
		return this.asBukkitMaterial.getNewData(legacyData);
	}
	
	public Material toMaterial() {
		return this.asBukkitMaterial;
	}
	
	public ItemStack toItemStack() {
		return this.asBukkitItemStack.clone();
	}
	
	public TranslatableItemStack toTranslatableItemStack(@Nullable String nameKey, @Nullable String loreKey) {
		return TranslatableItemStack.from(this.asBukkitItemStack, nameKey, loreKey);	
	}
	
	public TranslatableItemStack toTranslatableItemStack() {
		return TranslatableItemStack.from(this.asBukkitItemStack, null, null);
	}
	
	public boolean isEmpty() {
        switch (this) {
            case AIR:
            case CAVE_AIR:
            case VOID_AIR:
                return true;
            default:
            	return false;
        }
    }
	
	/**
	 * @returns true if ends with "_ITEM" (for legacy versions 1.12.2 and below)
	 */
	public boolean hasLegacyItemSuffix() {
		return this.legacyItemSuffix;
	}
	
	/**
	 * @returns true if it is a {@link BlockState} and not an {@link ItemStack}.
	 * <pre>
	 * Example: 
	 * PLAYER_WALL_HEAD (you cannot hold this in a inventory) returns true
	 * PLAYER_HEAD (but you can hold this) returns false
	 */
	public boolean isBlockState() {
		return this.blockState;
	}
	
	static {
		for (CoreMaterial cm : VALUES) {
			cm.asBukkitMaterial = matchMaterial(cm, true);
			cm.legacyItemSuffix = hasLegacyItemSuffix(cm);
			
			CoreMaterial stateToBlock = blockStateToItem(cm);
			cm.blockState = stateToBlock != cm;
			cm.asBukkitItemStack = matchItemStack(stateToBlock, true);
		}
	}
	
	@NotNull
	public static CoreMaterial[] asArray() {
		return VALUES;
	}
	
	@NotNull
	public static CoreMaterial getByOrdinal(int ordinal) {
		return VALUES[Numbers.checkRange(ordinal, 0, VALUES.length - 1)];
	}
	
	@Nullable
	public static CoreMaterial getByName(String name) {
		Objects.requireNonNull(name, "cannot get core material by null name!");
		return CORE_MATERIAL_MAPPINGS.get(name.toUpperCase(Locale.ENGLISH));
	}
	
	@Nullable
	public static Material getBukkitMaterialByName(String name) {
		Objects.requireNonNull(name, "cannot get material by null name!");
		return BukkitUtils.MATERIAL_MAPPINGS.get(name.toUpperCase(Locale.ENGLISH));
	}
	
	@Nullable
	public static CoreMaterial toCore(Material material) {
		for (int i = 0; i < VALUES.length; i++) {
			if (VALUES[i].asBukkitMaterial == material) {
				return VALUES[i];
			}
		}
		return null;
	}
	
	/**
	 * @param name name of material
	 * @returns if matches, matched value or else "STONE"
	 */
	@NotNull
	public static CoreMaterial matchByName(@NotNull String name) {
		return matchByName(name, true);
	}
	
	/**
	 * @param name name of material
	 * @param logReturns sends a message to the console when the value does not match
	 * @returns if matches, matched value or else "STONE"
	 */
	@NotNull
	public static CoreMaterial matchByName(@NotNull String name, boolean logReturns) {
		CoreMaterial match = getByName(name);
		
		if (match == null && logReturns) {
			
			Bukkit.getServer().getLogger()
			.log(Level.SEVERE, "[Core Material] No match found for \"" + name + "\" core material! Returning as \"STONE\"");
			
			return CoreMaterial.STONE;
		}
		
		return match;
	}
	
	@NotNull
	private static Material matchMaterial(@NotNull CoreMaterial nnmaterial, boolean logReturns) {
		Material match = BukkitUtils.MATERIAL_MAPPINGS.get(nnmaterial.name());
		if (match == null) {
			boolean log = nnmaterial.customTranslation;
			if (nnmaterial.reflectedValues != null) {
				for (String oValue : nnmaterial.reflectedValues) {
					match = BukkitUtils.MATERIAL_MAPPINGS.get(oValue);
					if (match == null) continue;
					
					if (log && logReturns) {
						
						Bukkit.getServer().getLogger()
						.log(Level.WARNING, "[Core Material] Match found for \"" + nnmaterial + "\" material! Return Value: \"" + oValue + "\"");
					}
					
					return match;
				}
			}
			
			if (match == null && nnmaterial.linkedValue != null) {
				return matchMaterial(nnmaterial.linkedValue, logReturns);
			} else {
				
				Bukkit.getServer().getLogger()
				.log(Level.SEVERE, "[Core Material] No match found for \"" + nnmaterial + "\" material! Returning as \"STONE\"");
				
				return Material.STONE;
			}
		}
		return match;
	}
	
	@NotNull
	private static ItemStack matchItemStack(@NotNull CoreMaterial coreMaterial, boolean logReturns) {
		Material match = matchMaterial(coreMaterial, logReturns);
		try {
			if (ServerVersion.isLegacy()) {
				return new ItemStack(coreMaterial.legacyItemSuffix ? BukkitUtils.MATERIAL_MAPPINGS.get(match.name() + "_ITEM") : match, 1, (byte) coreMaterial.legacyData);
			} else {
				return new ItemStack(match, 1);
			}
		} catch (Exception x) {
			
			Bukkit.getServer().getLogger()
			.log(Level.SEVERE, "[Core Material] No match found for \"" + coreMaterial + "\" item! Returning as \"STONE\"");
			
			return new ItemStack(Material.STONE);
		}
	}
	
	/**
	 * @returns true if ends with "_ITEM" (for legacy versions 1.12.2 and below)
	 */
	private static boolean hasLegacyItemSuffix(@NotNull CoreMaterial coreMaterial) {
		Objects.requireNonNull(coreMaterial, "coreMaterial cannot be null!");
		switch (coreMaterial) {
		case ACACIA_DOOR:
		case DARK_OAK_DOOR:
		case BIRCH_DOOR:
		case JUNGLE_DOOR:
		case SPRUCE_DOOR:
		case NETHER_BRICK:
		case CARROT:
		case POTATO:
		case FLOWER_POT:
		case CAULDRON:
		case BREWING_STAND:
		case PLAYER_HEAD:
		case ZOMBIE_HEAD:
		case SKELETON_SKULL:
			return true;
		default:
			return false;
		}
	}
	
	/**
	 * @returns to matched {@link ItemStack} of the {@link BlockState}.
	 * <pre>
	 * Example: 
	 * PLAYER_WALL_HEAD (returns PLAYER_HEAD)
	 * PLAYER_HEAD (returns PLAYER_HEAD)
	 */
	@NotNull
	private static CoreMaterial blockStateToItem(@NotNull CoreMaterial coreMaterial) {
		Objects.requireNonNull(coreMaterial, "cannot get item from null coreMaterial!");
		switch (coreMaterial) {
		case ACACIA_WALL_HANGING_SIGN:
			return CoreMaterial.ACACIA_HANGING_SIGN;
		case ACACIA_WALL_SIGN:
			return CoreMaterial.ACACIA_SIGN;
		case ATTACHED_MELON_STEM:
			return CoreMaterial.MELON_SEEDS;
		case ATTACHED_PUMPKIN_STEM:
			return CoreMaterial.PUMPKIN_SEEDS;
		case BAMBOO_SAPLING:
			return CoreMaterial.BAMBOO;
		case BAMBOO_WALL_HANGING_SIGN:
			return CoreMaterial.BAMBOO_HANGING_SIGN;
		case BAMBOO_WALL_SIGN:
			return CoreMaterial.BAMBOO_SIGN;
		case BEETROOTS:
			return CoreMaterial.BEETROOT;
		case BIG_DRIPLEAF_STEM:
			return CoreMaterial.BIG_DRIPLEAF;
		case BIRCH_WALL_HANGING_SIGN:
			return CoreMaterial.BIRCH_HANGING_SIGN;
		case BIRCH_WALL_SIGN:
			return CoreMaterial.BIRCH_SIGN;
		case BLACK_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case BLACK_WALL_BANNER:
			return CoreMaterial.BLACK_BANNER;
		case BLUE_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case BLUE_WALL_BANNER:
			return CoreMaterial.BLUE_BANNER;
		case BRAIN_CORAL_WALL_FAN:
			return CoreMaterial.BRAIN_CORAL_FAN;
		case BROWN_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case BROWN_WALL_BANNER:
			return CoreMaterial.BROWN_BANNER;
		case BUBBLE_COLUMN:
			return CoreMaterial.WATER_BUCKET;
		case BUBBLE_CORAL_WALL_FAN:
			return CoreMaterial.BUBBLE_CORAL_FAN;
		case CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case CARROTS:
			return CoreMaterial.CARROT;
		case CAVE_AIR:
			return CoreMaterial.BARRIER;
		case CAVE_VINES:
			return CoreMaterial.GLOW_BERRIES;
		case CAVE_VINES_PLANT:
			return CoreMaterial.GLOW_BERRIES;
		case CHERRY_WALL_HANGING_SIGN:
			return CoreMaterial.CHERRY_HANGING_SIGN;
		case CHERRY_WALL_SIGN:
			return CoreMaterial.CHERRY_SIGN;
		case COCOA:
			return CoreMaterial.COCOA_BEANS;
		case CREEPER_WALL_HEAD:
			return CoreMaterial.CREEPER_HEAD;
		case CRIMSON_WALL_HANGING_SIGN:
			return CoreMaterial.CRIMSON_HANGING_SIGN;
		case CRIMSON_WALL_SIGN:
			return CoreMaterial.CRIMSON_SIGN;
		case CYAN_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case CYAN_WALL_BANNER:
			return CoreMaterial.CYAN_BANNER;
		case DARK_OAK_WALL_HANGING_SIGN:
			return CoreMaterial.DARK_OAK_HANGING_SIGN;
		case DARK_OAK_WALL_SIGN:
			return CoreMaterial.DARK_OAK_SIGN;
		case DEAD_BRAIN_CORAL_WALL_FAN:
			return CoreMaterial.BRAIN_CORAL_FAN;
		case DEAD_BUBBLE_CORAL_WALL_FAN:
			return CoreMaterial.DEAD_BUBBLE_CORAL_FAN;
		case DEAD_FIRE_CORAL_WALL_FAN:
			return CoreMaterial.DEAD_FIRE_CORAL_FAN;
		case DEAD_HORN_CORAL_WALL_FAN:
			return CoreMaterial.DEAD_HORN_CORAL_FAN;
		case DEAD_TUBE_CORAL_WALL_FAN:
			return CoreMaterial.DEAD_TUBE_CORAL_FAN;
		case DRAGON_WALL_HEAD:
			return CoreMaterial.DRAGON_HEAD;
		case END_GATEWAY:
			return CoreMaterial.END_PORTAL_FRAME;
		case END_PORTAL:
			return CoreMaterial.END_PORTAL_FRAME;
		case FIRE:
			return CoreMaterial.FLINT_AND_STEEL;
		case FIRE_CORAL_WALL_FAN:
			return CoreMaterial.FIRE_CORAL_FAN;
		case FROSTED_ICE:
			return CoreMaterial.ICE;
		case GRAY_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case GRAY_WALL_BANNER:
			return CoreMaterial.GRAY_BANNER;
		case GREEN_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case GREEN_WALL_BANNER:
			return CoreMaterial.GREEN_BANNER;
		case HORN_CORAL_WALL_FAN:
			return CoreMaterial.HORN_CORAL_FAN;
		case JUNGLE_WALL_HANGING_SIGN:
			return CoreMaterial.JUNGLE_HANGING_SIGN;
		case JUNGLE_WALL_SIGN:
			return CoreMaterial.JUNGLE_SIGN;
		case KELP_PLANT:
			return CoreMaterial.KELP;
		case LAVA:
			return CoreMaterial.LAVA_BUCKET;
		case LAVA_CAULDRON:
			return CoreMaterial.CAULDRON;
		case LIGHT_BLUE_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case LIGHT_BLUE_WALL_BANNER:
			return CoreMaterial.LIGHT_BLUE_BANNER;
		case LIGHT_GRAY_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case LIGHT_GRAY_WALL_BANNER:
			return CoreMaterial.LIGHT_GRAY_BANNER;
		case LIME_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case LIME_WALL_BANNER:
			return CoreMaterial.LIME_BANNER;
		case MAGENTA_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case MAGENTA_WALL_BANNER:
			return CoreMaterial.MAGENTA_BANNER;
		case MANGROVE_WALL_HANGING_SIGN:
			return CoreMaterial.MANGROVE_HANGING_SIGN;
		case MANGROVE_WALL_SIGN:
			return CoreMaterial.MANGROVE_SIGN;
		case MELON_STEM:
			return CoreMaterial.MELON_SEEDS;
		case MOVING_PISTON:
			return CoreMaterial.PISTON;
		case NETHER_PORTAL:
			return CoreMaterial.OBSIDIAN;
		case OAK_WALL_HANGING_SIGN:
			return CoreMaterial.OAK_HANGING_SIGN;
		case OAK_WALL_SIGN:
			return CoreMaterial.OAK_SIGN;
		case ORANGE_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case ORANGE_WALL_BANNER:
			return CoreMaterial.ORANGE_BANNER;
		case PIGLIN_WALL_HEAD:
			return CoreMaterial.PIGLIN_HEAD;
		case PINK_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case PINK_WALL_BANNER:
			return CoreMaterial.PINK_BANNER;
		case PISTON_HEAD:
			return CoreMaterial.PISTON;
		case PITCHER_CROP:
			return CoreMaterial.PITCHER_PLANT;
		case PLAYER_WALL_HEAD:
			return CoreMaterial.PLAYER_HEAD;
		case POTATOES:
			return CoreMaterial.POTATO;
		case POTTED_ACACIA_SAPLING:
			return CoreMaterial.ACACIA_SAPLING;
		case POTTED_ALLIUM:
			return CoreMaterial.ALLIUM;
		case POTTED_AZALEA_BUSH:
			return CoreMaterial.AZALEA;
		case POTTED_AZURE_BLUET:
			return CoreMaterial.AZURE_BLUET;
		case POTTED_BAMBOO:
			return CoreMaterial.BAMBOO;
		case POTTED_BIRCH_SAPLING:
			return CoreMaterial.BIRCH_SAPLING;
		case POTTED_BLUE_ORCHID:
			return CoreMaterial.BLUE_ORCHID;
		case POTTED_BROWN_MUSHROOM:
			return CoreMaterial.BROWN_MUSHROOM;
		case POTTED_CACTUS:
			return CoreMaterial.CACTUS;
		case POTTED_CHERRY_SAPLING:
			return CoreMaterial.CHERRY_SAPLING;
		case POTTED_CORNFLOWER:
			return CoreMaterial.CORNFLOWER;
		case POTTED_CRIMSON_FUNGUS:
			return CoreMaterial.CRIMSON_FUNGUS;
		case POTTED_CRIMSON_ROOTS:
			return CoreMaterial.CRIMSON_ROOTS;
		case POTTED_DANDELION:
			return CoreMaterial.DANDELION;
		case POTTED_DARK_OAK_SAPLING:
			return CoreMaterial.DARK_OAK_SAPLING;
		case POTTED_DEAD_BUSH:
			return CoreMaterial.DEAD_BUSH;
		case POTTED_FERN:
			return CoreMaterial.FERN;
		case POTTED_FLOWERING_AZALEA_BUSH:
			return CoreMaterial.FLOWERING_AZALEA;
		case POTTED_JUNGLE_SAPLING:
			return CoreMaterial.JUNGLE_SAPLING;
		case POTTED_LILY_OF_THE_VALLEY:
			return CoreMaterial.LILY_OF_THE_VALLEY;
		case POTTED_MANGROVE_PROPAGULE:
			return CoreMaterial.MANGROVE_PROPAGULE;
		case POTTED_OAK_SAPLING:
			return CoreMaterial.OAK_SAPLING;
		case POTTED_ORANGE_TULIP:
			return CoreMaterial.ORANGE_TULIP;
		case POTTED_OXEYE_DAISY:
			return CoreMaterial.OXEYE_DAISY;
		case POTTED_PINK_TULIP:
			return CoreMaterial.PINK_TULIP;
		case POTTED_POPPY:
			return CoreMaterial.POPPY;
		case POTTED_RED_MUSHROOM:
			return CoreMaterial.RED_MUSHROOM;
		case POTTED_RED_TULIP:
			return CoreMaterial.RED_TULIP;
		case POTTED_SPRUCE_SAPLING:
			return CoreMaterial.SPRUCE_SAPLING;
		case POTTED_TORCHFLOWER:
			return CoreMaterial.TORCHFLOWER;
		case POTTED_WARPED_FUNGUS:
			return CoreMaterial.WARPED_FUNGUS;
		case POTTED_WARPED_ROOTS:
			return CoreMaterial.WARPED_ROOTS;
		case POTTED_WHITE_TULIP:
			return CoreMaterial.WHITE_TULIP;
		case POTTED_WITHER_ROSE:
			return CoreMaterial.WITHER_ROSE;
		case POWDER_SNOW:
			return CoreMaterial.POWDER_SNOW_BUCKET;
		case POWDER_SNOW_CAULDRON:
			return CoreMaterial.CAULDRON;
		case PUMPKIN_STEM:
			return CoreMaterial.PUMPKIN_SEEDS;
		case PURPLE_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case PURPLE_WALL_BANNER:
			return CoreMaterial.PURPLE_BANNER;
		case RED_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case RED_WALL_BANNER:
			return CoreMaterial.RED_BANNER;
		case REDSTONE_WALL_TORCH:
			return CoreMaterial.REDSTONE_TORCH;
		case REDSTONE_WIRE:
			return CoreMaterial.REDSTONE;
		case SKELETON_WALL_SKULL:
			return CoreMaterial.SKELETON_SKULL;
		case SOUL_FIRE:
			return CoreMaterial.FLINT_AND_STEEL;
		case SOUL_WALL_TORCH:
			return CoreMaterial.SOUL_TORCH;
		case SPRUCE_WALL_HANGING_SIGN:
			return CoreMaterial.SPRUCE_HANGING_SIGN;
		case SPRUCE_WALL_SIGN:
			return CoreMaterial.SPRUCE_SIGN;
		case SWEET_BERRY_BUSH:
			return CoreMaterial.SWEET_BERRIES;
		case TALL_SEAGRASS:
			return CoreMaterial.SEAGRASS;
		case TORCHFLOWER_CROP:
			return CoreMaterial.TORCHFLOWER_SEEDS;
		case TRIPWIRE:
			return CoreMaterial.TRIPWIRE_HOOK;
		case TUBE_CORAL_WALL_FAN:
			return CoreMaterial.TUBE_CORAL_FAN;
		case TWISTING_VINES_PLANT:
			return CoreMaterial.TWISTING_VINES;
		case VOID_AIR:
			return CoreMaterial.BARRIER;
		case WALL_TORCH:
			return CoreMaterial.TORCH;
		case WARPED_WALL_HANGING_SIGN:
			return CoreMaterial.WARPED_HANGING_SIGN;
		case WARPED_WALL_SIGN:
			return CoreMaterial.WARPED_SIGN;
		case WATER:
			return CoreMaterial.WATER_BUCKET;
		case WATER_CAULDRON:
			return CoreMaterial.CAULDRON;
		case WEEPING_VINES_PLANT:
			return CoreMaterial.WEEPING_VINES;
		case WHITE_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case WHITE_WALL_BANNER:
			return CoreMaterial.WHITE_BANNER;
		case WITHER_SKELETON_WALL_SKULL:
			return CoreMaterial.WITHER_SKELETON_SKULL;
		case YELLOW_CANDLE_CAKE:
			return CoreMaterial.CAKE;
		case YELLOW_WALL_BANNER:
			return CoreMaterial.YELLOW_BANNER;
		case ZOMBIE_WALL_HEAD:
			return CoreMaterial.ZOMBIE_HEAD;
		default:
			return coreMaterial;
		}
	}
}
